# Labeling Time Analysis

How much time does a volunteer need to label a single image? This is an important question to answer in order to estimate the time needed to label a large dataset. In this notebook, we will analyze the time taken by volunteers to label images in the dataset.

In [10]:
import pandas as pd

from zooniverse.config import get_config
from pathlib import Path

phase_tag = "Iguanas 4th launch"

output_path = Path(f"/Users/christian/data/zooniverse/2024_09_27_analysis").joinpath(phase_tag)
output_path.mkdir(parents=True, exist_ok=True)
input_path = Path("/Users/christian/data/zooniverse")
config = get_config(phase_tag=phase_tag, input_path=input_path, output_path=output_path)

df_yes_no = pd.read_csv(config["yes_no_dataset"])

In [11]:
df_yes_no

,Unnamed: 0,phase_tag,subject_id,user_id,user_name,label_time,labeling_started_at,labeling_finished_at,value
0,0,Iguanas 4th launch,78861913,1983945.0,ANDREAVARELA89,2023-10-11 14:18:08 UTC,2023-10-11T14:17:25.953Z,2023-10-11T14:18:08.542Z,Yes
1,1,Iguanas 4th launch,92462758,1983945.0,ANDREAVARELA89,2023-10-16 10:10:44 UTC,2023-10-16T10:09:37.281Z,2023-10-16T10:10:44.739Z,Yes
2,2,Iguanas 4th launch,92464036,1983945.0,ANDREAVARELA89,2023-10-16 12:34:09 UTC,2023-10-16T12:32:57.585Z,2023-10-16T12:34:09.340Z,No
3,3,Iguanas 4th launch,92464442,1983945.0,ANDREAVARELA89,2023-10-16 12:36:25 UTC,2023-10-16T12:34:09.359Z,2023-10-16T12:36:24.458Z,Yes
4,4,Iguanas 4th launch,92462615,NaN,not-logged-in-6b54a3e3534e75ce1641,2023-10-16 12:49:03 UTC,2023-10-16T12:46:09.184Z,2023-10-16T12:49:02.703Z,No
...,...,...,...,...,...,...,...,...,...
202316,202316,Iguanas 4th launch,92460149,2606938.0,Ramalina,2024-07-03 09:36:00 UTC,2024-07-01T08:17:53.116Z,2024-07-03T09:35:59.583Z,No
202317,202317,Iguanas 4th launch,92463653,2606938.0,Ramalina,2024-07-03 09:36:57 UTC,2024-07-03T09:35:59.595Z,2024-07-03T09:36:57.206Z,No
202318,202318,Iguanas 4th launch,92461607,2606938.0,Ramalina,2024-07-03 09:38:38 UTC,2024-07-03T09:36:57.213Z,2024-07-03T09:38:38.111Z,No
202319,202319,Iguanas 4th launch,92458660,2606938.0,Ramalina,2024-07-03 09:40:06 UTC,2024-07-03T09:38:38.118Z,2024-07-03T09:40:06.566Z,No
202320,202320,Iguanas 4th launch,92460485,2606938.0,Ramalina,2024-07-03 09:41:28 UTC,2024-07-03T09:40:06.574Z,2024-07-03T09:41:28.398Z,No

In [12]:
df_yes_no["labeling_started_at"] = pd.to_datetime(df_yes_no["labeling_started_at"])
df_yes_no["labeling_finished_at"] = pd.to_datetime(df_yes_no["labeling_finished_at"])

df_yes_no["time_spent"] =  df_yes_no['labeling_finished_at'] - df_yes_no['labeling_started_at']
df_yes_no["time_spent"]

0        0 days 00:00:42.589000
1        0 days 00:01:07.458000
2        0 days 00:01:11.755000
3        0 days 00:02:15.099000
4        0 days 00:02:53.519000
                  ...
202316   2 days 01:18:06.467000
202317   0 days 00:00:57.611000
202318   0 days 00:01:40.898000
202319   0 days 00:01:28.448000
202320   0 days 00:01:21.824000
Name: time_spent, Length: 202321, dtype: timedelta64[ns]

In [13]:
df_yes_no

,Unnamed: 0,phase_tag,subject_id,user_id,user_name,label_time,labeling_started_at,labeling_finished_at,value,time_spent
0,0,Iguanas 4th launch,78861913,1983945.0,ANDREAVARELA89,2023-10-11 14:18:08 UTC,2023-10-11 14:17:25.953000+00:00,2023-10-11 14:18:08.542000+00:00,Yes,0 days 00:00:42.589000
1,1,Iguanas 4th launch,92462758,1983945.0,ANDREAVARELA89,2023-10-16 10:10:44 UTC,2023-10-16 10:09:37.281000+00:00,2023-10-16 10:10:44.739000+00:00,Yes,0 days 00:01:07.458000
2,2,Iguanas 4th launch,92464036,1983945.0,ANDREAVARELA89,2023-10-16 12:34:09 UTC,2023-10-16 12:32:57.585000+00:00,2023-10-16 12:34:09.340000+00:00,No,0 days 00:01:11.755000
3,3,Iguanas 4th launch,92464442,1983945.0,ANDREAVARELA89,2023-10-16 12:36:25 UTC,2023-10-16 12:34:09.359000+00:00,2023-10-16 12:36:24.458000+00:00,Yes,0 days 00:02:15.099000
4,4,Iguanas 4th launch,92462615,NaN,not-logged-in-6b54a3e3534e75ce1641,2023-10-16 12:49:03 UTC,2023-10-16 12:46:09.184000+00:00,2023-10-16 12:49:02.703000+00:00,No,0 days 00:02:53.519000
...,...,...,...,...,...,...,...,...,...,...
202316,202316,Iguanas 4th launch,92460149,2606938.0,Ramalina,2024-07-03 09:36:00 UTC,2024-07-01 08:17:53.116000+00:00,2024-07-03 09:35:59.583000+00:00,No,2 days 01:18:06.467000
202317,202317,Iguanas 4th launch,92463653,2606938.0,Ramalina,2024-07-03 09:36:57 UTC,2024-07-03 09:35:59.595000+00:00,2024-07-03 09:36:57.206000+00:00,No,0 days 00:00:57.611000
202318,202318,Iguanas 4th launch,92461607,2606938.0,Ramalina,2024-07-03 09:38:38 UTC,2024-07-03 09:36:57.213000+00:00,2024-07-03 09:38:38.111000+00:00,No,0 days 00:01:40.898000
202319,202319,Iguanas 4th launch,92458660,2606938.0,Ramalina,2024-07-03 09:40:06 UTC,2024-07-03 09:38:38.118000+00:00,2024-07-03 09:40:06.566000+00:00,No,0 days 00:01:28.448000
202320,202320,Iguanas 4th launch,92460485,2606938.0,Ramalina,2024-07-03 09:41:28 UTC,2024-07-03 09:40:06.574000+00:00,2024-07-03 09:41:28.398000+00:00,No,0 days 00:01:21.824000

In [14]:
df_yes_no.groupby("subject_id")["time_spent"].sum()

subject_id
78861913   0 days 00:00:42.589000
92458387   0 days 21:51:27.507000
92458388   0 days 00:14:27.588000
92458389   0 days 00:38:47.585000
92458390   0 days 00:45:18.273000
                    ...
92469731   0 days 00:10:56.627000
92469733   0 days 00:12:02.535000
92469734   0 days 00:25:15.334000
92469735   0 days 00:15:39.064000
92469736   0 days 00:26:50.153000
Name: time_spent, Length: 9929, dtype: timedelta64[ns]

In [16]:
df_yes_no.groupby("subject_id")["time_spent"].sum().describe()

count                         9929
mean     0 days 02:15:05.295936549
std      0 days 14:45:04.512830329
min      -35 days +22:39:35.147000
25%         0 days 00:12:43.322000
50%         0 days 00:19:09.795000
75%         0 days 00:32:54.566000
max        21 days 01:07:26.495000
Name: time_spent, dtype: object

In [17]:
df_yes_no.groupby("subject_id")["time_spent"].sum().median()

Timedelta('0 days 00:19:09.795000')