# Using the Panoptes Aggregation Tool from Zooniverse
See Readme for the installation instructions.


This notebook combines the aggregation steps from the raw classification from zooniverse.
Installed from github, https://aggregation-caesar.zooniverse.org/Scripts.html#scripts
The latest pypi release is from 2020 and I can't install it: https://pypi.org/project/panoptes-aggregation/

When using the aggregation tool, the following steps are necessary:
- change input_path and output_path to your local paths. Those will be necessary later i.e. for plots.
- adobt "subjects_path" for the subjects file and "annotations_source" for the classification file in config.py
- later in the section Panoptes Data Extraction change the paths acordingly
- change the paths to the classification files in the panoptes extraction sections. At first this is in the config file "config.py"

In [1]:
# install the aggregation tool
!pip install -U git+https://github.com/zooniverse/aggregation-for-caesar.git

# this worked with panoptes-aggregation version 4.1.0

!pip show panoptes-aggregation

Collecting git+https://github.com/zooniverse/aggregation-for-caesar.git
  Cloning https://github.com/zooniverse/aggregation-for-caesar.git to /private/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/pip-req-build-0fjt8p32
  Running command git clone --filter=blob:none --quiet https://github.com/zooniverse/aggregation-for-caesar.git /private/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/pip-req-build-0fjt8p32
  Resolved https://github.com/zooniverse/aggregation-for-caesar.git to commit c8a9fffb5228b962515eecd96e852ae0aebaa681
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4<4.13,>=4.8.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (4.12.3)
Requirement already satisfied: collatex<2.4,>=2.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (2.3)
Requirement already satisfied: hdbscan<=0.8.33,>=0.8.20 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (0.8.33)
Requirement already satisfied: lxml<4.10,>=4.4 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (4.9.4)
Requirement already satisfied: numpy<1.26.3,>=1.22.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (1.26.2)
Requirement already satisfied: packaging<23.3,>=20.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (23.2)
Requirement already satisfied: pandas<2.1.4,>=1.4.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (2.1.3)
Requirement already satisfied: progressbar2<4.3,>=3.39 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (4.2.0)
Requirement already satisfied: python-levenshtein<0.24,>=0.21.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (0.23.0)
Requirement already satisfied: python-slugify<8.1,>=7.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (8.0.4)
Requirement already satisfied: pyyaml<6.1,>=6.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (6.0.2)
Requirement already satisfied: scikit-learn<1.3.3,>=1.2.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (1.3.2)
Requirement already satisfied: scipy<1.11.4,>=1.10.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (1.11.3)
Requirement already satisfied: werkzeug<3.0.2,>=2.3.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (3.0.1)
Requirement already satisfied: shapely<2.0.3,>=2.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from panoptes_aggregation==4.1.0) (2.0.2)
Requirement already satisfied: soupsieve>1.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from beautifulsoup4<4.13,>=4.8.1->panoptes_aggregation==4.1.0) (2.6)
Requirement already satisfied: networkx in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from collatex<2.4,>=2.3->panoptes_aggregation==4.1.0) (3.3)
Requirement already satisfied: prettytable in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from collatex<2.4,>=2.3->panoptes_aggregation==4.1.0) (3.11.0)
Requirement already satisfied: cython<3,>=0.27 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from hdbscan<=0.8.33,>=0.8.20->panoptes_aggregation==4.1.0) (0.29.37)
Requirement already satisfied: joblib>=1.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from hdbscan<=0.8.33,>=0.8.20->panoptes_aggregation==4.1.0) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pandas<2.1.4,>=1.4.0->panoptes_aggregation==4.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pandas<2.1.4,>=1.4.0->panoptes_aggregation==4.1.0) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pandas<2.1.4,>=1.4.0->panoptes_aggregation==4.1.0) (2024.1)
Requirement already satisfied: python-utils>=3.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from progressbar2<4.3,>=3.39->panoptes_aggregation==4.1.0) (3.8.2)
Requirement already satisfied: Levenshtein==0.23.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from python-levenshtein<0.24,>=0.21.0->panoptes_aggregation==4.1.0) (0.23.0)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.1.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from Levenshtein==0.23.0->python-levenshtein<0.24,>=0.21.0->panoptes_aggregation==4.1.0) (3.9.7)
Requirement already satisfied: text-unidecode>=1.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from python-slugify<8.1,>=7.0.0->panoptes_aggregation==4.1.0) (1.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from scikit-learn<1.3.3,>=1.2.0->panoptes_aggregation==4.1.0) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from werkzeug<3.0.2,>=2.3.0->panoptes_aggregation==4.1.0) (2.1.5)
Requirement already satisfied: six>=1.5 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<2.1.4,>=1.4.0->panoptes_aggregation==4.1.0) (1.16.0)
Requirement already satisfied: typing-extensions>3.10.0.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from python-utils>=3.0.0->progressbar2<4.3,>=3.39->panoptes_aggregation==4.1.0) (4.12.2)
Requirement already satisfied: wcwidth in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from prettytable->collatex<2.4,>=2.3->panoptes_aggregation==4.1.0) (0.2.13)
Name: panoptes_aggregation
Version: 4.1.0
Summary: Aggregation code for Zooniverse panoptes projects.
Home-page:
Author:
Author-email: Coleman Krawczyk <coleman@zooniverse.org>
License:
Location: /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages
Requires: beautifulsoup4, collatex, hdbscan, lxml, numpy, packaging, pandas, progressbar2, python-levenshtein, python-slugify, pyyaml, scikit-learn, scipy, shapely, werkzeug
Required-by:

In [2]:
# !pip uninstall -y panoptes_aggregation

In [3]:
## This does not work because they are not updating their packages anymore
# !pip install panoptes_aggregation

In [4]:
!pip install -r requirements-dev.txt

Requirement already satisfied: matplotlib in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 1)) (3.9.2)
Requirement already satisfied: jupyterlab in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 2)) (4.2.5)
Requirement already satisfied: pandas in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 3)) (2.1.3)
Requirement already satisfied: scikit-learn in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 4)) (1.3.2)
Requirement already satisfied: kneed in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 5)) (0.8.5)
Requirement already satisfied: loguru in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 6)) (0.7.2)
Requirement already satisfied: black in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 7)) (24.8.0)
Requirement already satisfied: pytest in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 8)) (8.3.2)
Requirement already satisfied: seaborn in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 9)) (0.13.2)
Requirement already satisfied: jupyter in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from -r requirements-dev.txt (line 10)) (1.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (1.4.7)
Requirement already satisfied: numpy>=1.23 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (23.2)
Requirement already satisfied: pillow>=8 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from matplotlib->-r requirements-dev.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: async-lru>=1.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (0.27.2)
Requirement already satisfied: ipykernel>=6.5.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (6.29.5)
Requirement already satisfied: jinja2>=3.0.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (3.1.4)
Requirement already satisfied: jupyter-core in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (5.7.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (2.14.2)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (0.2.4)
Requirement already satisfied: setuptools>=40.1.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (73.0.1)
Requirement already satisfied: tomli>=1.2.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (2.0.1)
Requirement already satisfied: tornado>=6.2.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (6.4.1)
Requirement already satisfied: traitlets in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab->-r requirements-dev.txt (line 2)) (5.14.3)
Requirement already satisfied: pytz>=2020.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pandas->-r requirements-dev.txt (line 3)) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pandas->-r requirements-dev.txt (line 3)) (2024.1)
Requirement already satisfied: scipy>=1.5.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from scikit-learn->-r requirements-dev.txt (line 4)) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from scikit-learn->-r requirements-dev.txt (line 4)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from scikit-learn->-r requirements-dev.txt (line 4)) (3.5.0)
Requirement already satisfied: click>=8.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from black->-r requirements-dev.txt (line 7)) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from black->-r requirements-dev.txt (line 7)) (1.0.0)
Requirement already satisfied: pathspec>=0.9.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from black->-r requirements-dev.txt (line 7)) (0.12.1)
Requirement already satisfied: platformdirs>=2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from black->-r requirements-dev.txt (line 7)) (4.2.2)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from black->-r requirements-dev.txt (line 7)) (4.12.2)
Requirement already satisfied: iniconfig in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pytest->-r requirements-dev.txt (line 8)) (2.0.0)
Requirement already satisfied: pluggy<2,>=1.5 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pytest->-r requirements-dev.txt (line 8)) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from pytest->-r requirements-dev.txt (line 8)) (1.2.2)
Requirement already satisfied: notebook in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter->-r requirements-dev.txt (line 10)) (7.2.2)
Requirement already satisfied: jupyter-console in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter->-r requirements-dev.txt (line 10)) (6.6.3)
Requirement already satisfied: nbconvert in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter->-r requirements-dev.txt (line 10)) (7.16.4)
Requirement already satisfied: ipywidgets in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter->-r requirements-dev.txt (line 10)) (8.1.5)
Requirement already satisfied: anyio in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (4.4.0)
Requirement already satisfied: certifi in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.0.5)
Requirement already satisfied: idna in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (3.8)
Requirement already satisfied: sniffio in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.14.0)
Requirement already satisfied: appnope in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.8.5)
Requirement already satisfied: ipython>=7.23.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (8.27.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (8.6.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.1.7)
Requirement already satisfied: nest-asyncio in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.6.0)
Requirement already satisfied: psutil in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (6.0.0)
Requirement already satisfied: pyzmq>=24 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipykernel>=6.5.0->jupyterlab->-r requirements-dev.txt (line 2)) (26.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jinja2>=3.0.3->jupyterlab->-r requirements-dev.txt (line 2)) (2.1.5)
Requirement already satisfied: argon2-cffi>=21.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (23.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.20.0)
Requirement already satisfied: send2trash>=1.8.2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (1.8.0)
Requirement already satisfied: babel>=2.10 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->-r requirements-dev.txt (line 2)) (2.16.0)
Requirement already satisfied: json5>=0.9.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->-r requirements-dev.txt (line 2)) (0.9.25)
Requirement already satisfied: jsonschema>=4.18.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->-r requirements-dev.txt (line 2)) (4.23.0)
Requirement already satisfied: requests>=2.31 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->-r requirements-dev.txt (line 2)) (2.32.3)
Requirement already satisfied: beautifulsoup4 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (6.1.0)
Requirement already satisfied: defusedxml in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (0.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (2.18.0)
Requirement already satisfied: tinycss2 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from nbconvert->jupyter->-r requirements-dev.txt (line 10)) (1.3.0)
Requirement already satisfied: six>=1.5 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->-r requirements-dev.txt (line 1)) (1.16.0)
Requirement already satisfied: widgetsnbextension~=4.0.12 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipywidgets->jupyter->-r requirements-dev.txt (line 10)) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from ipywidgets->jupyter->-r requirements-dev.txt (line 10)) (3.0.13)
Requirement already satisfied: prompt-toolkit>=3.0.30 in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from jupyter-console->jupyter->-r requirements-dev.txt (line 10)) (3.0.47)
Requirement already satisfied: argon2-cffi-bindings in /Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->-r requirements-dev.txt (line 2)) (21.2.0)

In [5]:
from zooniverse.config import get_config
import pandas as pd
from pathlib import Path

### use either the subset of the subset
#phase_tag = "Iguanas 1st launch"
#data_folder = "./data/phase_1"
## 

# phase_tag = "Iguanas 2nd launch"
# data_folder = "./data/phase_2"

# phase_tag = "Iguanas 3rd launch"
# data_folder = "./data/phase_3"

phase_tag = "Iguanas 4th launch"
data_folder = "./data/phase_4"

# 
input_path = Path("/Users/christian/data/zooniverse")
# use_gold_standard_subset = "expert" # Use the expert-GS-Xphase as the basis


output_path = Path("/Users/christian/data/zooniverse/2024_09_25_analysis").joinpath(phase_tag).resolve()

workflow_id_p1 = 14370.0
workflow_id_p2 = 20600.0
workflow_id_p3 = 22040.0
workflow_id_p4 = 25351.0

output_plot_path = output_path.joinpath("plots")
output_plot_path.mkdir(parents=True, exist_ok=True)

reprocess = False

config = get_config(phase_tag=phase_tag, input_path=input_path, output_path=output_path)
config

{'annotations_source': PosixPath('/Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv'),
 'goldstandard_data': PosixPath('/Users/christian/data/zooniverse/Images/Zooniverse_Goldstandard_images/expert-GS-4thphase_renamed.csv'),
 'gold_standard_image_subset': PosixPath('/Users/christian/data/zooniverse/Images/Zooniverse_Goldstandard_images/4-T2-GS-results-5th-0s.csv'),
 'image_source': None,
 'subjects_path': PosixPath('/Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-subjects.csv'),
 'yes_no_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/yes_no_dataset_Iguanas 4th launch.csv'),
 'flat_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/flat_dataset_Iguanas 4th launch.csv'),
 'flat_panoptes_points': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/flat_panoptes_points_Iguanas 4th launch.csv'),
 'panoptes_question': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/panoptes_question_Iguanas 4th launch.csv'),
 'merged_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/flat_dataset_filtered_Iguanas 4th launch.csv'),
 'gold_standard_and_expert_count': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_gold_standard_and_expert_count.csv'),
 'comparison_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison.csv'),
 'comparison_dataset_expert': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison_expert.csv'),
 'comparison_dataset_yes_no': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison_yes_no.csv'),
 'method_sums': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_method_sums.csv'),
 'rmse_errors': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_rmse_errors.csv'),
 'dbscan_hyperparam_grid': PosixPath('/Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/Iguanas 4th launch_hyperparam_grid.csv')}

# Look into the subjects file
This contains the mappings from the subject_id to the image file

In [6]:
# read the original subjects file
df_subjects = pd.read_csv(config["subjects_path"], sep=",")

# filter the subjects for only the images in the three phases

df_subjects = df_subjects[df_subjects.workflow_id.isin([workflow_id_p1, workflow_id_p2, workflow_id_p3, workflow_id_p4])]

# inspect the metadata
import json
def get_json_keys(json_str):
    try:
        json_obj = json.loads(json_str)
        return list(json_obj.keys())
    except json.JSONDecodeError:
        return []

# Apply the function to each row in the metadata column and collect all keys
all_keys = df_subjects['locations'].apply(get_json_keys)

# Flatten the list of lists and get unique keys
unique_keys = set([key for sublist in all_keys for key in sublist])

print(unique_keys)

{'0'}

Clean up the subjects file for inconsistent naming.

In [7]:
df_subjects["image_name"] = df_subjects['metadata'].apply(lambda x: json.loads(x).get('Image_name') 
                                        or json.loads(x).get('image_name') 
                                        or json.loads(x).get('Filename')).sort_values(ascending=True)

# 'site', 'flight', 'Flight', 'Site', 'flight_code' depict the same
df_subjects["flight_code"] = df_subjects['metadata'].apply(lambda x: json.loads(x).get('flight_code') 
                                        or json.loads(x).get('site') 
                                        or json.loads(x).get('flight')
                                        or json.loads(x).get('Flight')
                                        or json.loads(x).get('Site')).sort_values(ascending=True)

df_subjects["url"] = df_subjects['locations'].apply(lambda x: json.loads(x)["0"])
df_subjects["filepath"] = None

In [8]:
df_subjects

,subject_id,project_id,workflow_id,subject_set_id,metadata,locations,classifications_count,retired_at,retirement_reason,created_at,updated_at,image_name,flight_code,url,filepath
190,47967468,11905,14370.0,86008,"{""site"":""SFB"",""image_name"":""SFB01-3_08.jpg"",""s...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2020-11-15 19:06:16 UTC,classification_count,2020-07-18 20:38:14 UTC,2020-07-18 20:38:14 UTC,SFB01-3_08.jpg,SFB,https://panoptes-uploads.zooniverse.org/subjec...,None
191,47967469,11905,14370.0,86008,"{""site"":""SFB"",""image_name"":""SFB01-3_15.jpg"",""s...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2020-10-28 19:25:18 UTC,classification_count,2020-07-18 20:38:17 UTC,2020-07-18 20:38:17 UTC,SFB01-3_15.jpg,SFB,https://panoptes-uploads.zooniverse.org/subjec...,None
192,47967470,11905,14370.0,86008,"{""site"":""SFB"",""image_name"":""SFB01-3_27.jpg"",""s...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2020-11-14 10:07:19 UTC,classification_count,2020-07-18 20:38:18 UTC,2020-07-18 20:38:18 UTC,SFB01-3_27.jpg,SFB,https://panoptes-uploads.zooniverse.org/subjec...,None
193,47967471,11905,14370.0,86008,"{""site"":""SFB"",""image_name"":""SFB01-3_28.jpg"",""s...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2020-11-09 10:36:02 UTC,classification_count,2020-07-18 20:38:20 UTC,2020-07-18 20:38:20 UTC,SFB01-3_28.jpg,SFB,https://panoptes-uploads.zooniverse.org/subjec...,None
194,47967472,11905,14370.0,86008,"{""site"":""SFB"",""image_name"":""SFB01-3_34.jpg"",""s...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2020-11-18 20:44:36 UTC,classification_count,2020-07-18 20:38:22 UTC,2020-07-18 20:38:22 UTC,SFB01-3_34.jpg,SFB,https://panoptes-uploads.zooniverse.org/subjec...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68155,92469731,11905,25351.0,116619,"{""Site"":""Puerto Villamil"",""Island"":""Isabela"",""...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2024-05-22 05:12:27 UTC,classification_count,2023-10-12 16:28:45 UTC,2023-10-12 16:28:45 UTC,Isa_ISVB02_27012023_155.jpg,Puerto Villamil,https://panoptes-uploads.zooniverse.org/subjec...,None
68156,92469733,11905,25351.0,116619,"{""Site"":""Puerto Villamil"",""Island"":""Isabela"",""...","{""0"":""https://panoptes-uploads.zooniverse.org/...",19,2024-04-13 19:24:15 UTC,classification_count,2023-10-12 16:28:46 UTC,2023-10-12 16:28:46 UTC,Isa_ISVB01_27012023_75_36.jpg,Puerto Villamil,https://panoptes-uploads.zooniverse.org/subjec...,None
68157,92469734,11905,25351.0,116619,"{""Site"":""Puerto Villamil"",""Island"":""Isabela"",""...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2024-04-21 08:49:10 UTC,classification_count,2023-10-12 16:28:46 UTC,2023-10-12 16:28:46 UTC,Isa_ISVB01_27012023_27_16.jpg,Puerto Villamil,https://panoptes-uploads.zooniverse.org/subjec...,None
68158,92469735,11905,25351.0,116619,"{""Site"":""Puerto Villamil"",""Island"":""Isabela"",""...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2024-06-26 17:32:21 UTC,classification_count,2023-10-12 16:28:46 UTC,2023-10-12 16:28:46 UTC,Isa_ISVB03_77012023_28_17.jpg,Puerto Villamil,https://panoptes-uploads.zooniverse.org/subjec...,None
68159,92469736,11905,25351.0,116619,"{""Site"":""Puerto Villamil"",""Island"":""Isabela"",""...","{""0"":""https://panoptes-uploads.zooniverse.org/...",20,2024-05-18 12:13:54 UTC,classification_count,2023-10-12 16:28:47 UTC,2023-10-12 16:28:47 UTC,Isa_ISVB01_27012023_51_37.jpg,Puerto Villamil,https://panoptes-uploads.zooniverse.org/subjec...,None

helper function to download the images using the urls in the subjects file

In [9]:
from loguru import logger
from time import sleep

import requests

def download_image(url, filename):
    """Download an image from a URL and save it to a file."""
    try:
        response = requests.get(url)
        if response.status_code == 200:
            with open(filename, 'wb') as file:
                file.write(response.content)
            return True
        else:
            logger.warning(f"Failed to download {url}")
            logger.error(response)
            sleep(5)
            return False
    except Exception as e:
        logger.error(e)
        sleep(5)
        return False

# Panoptes Data Extraction from Zooniverse
## Panoptes config
### Create the configuration files automatically
The configurations were changed to custom workflow versions.

In [10]:
# create a configuration file from the workflow
#!mkdir ./data/phase_1
#! panoptes_aggregation config /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-workflows.csv 14370 --min_version 0 --max_version 142.245 -d ./data/phase_1
# 
#!mkdir ./data/phase_2
#! panoptes_aggregation config /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-workflows.csv 20600 --min_version 0 --max_version 94.166 -d ./data/phase_2
# 
#!mkdir ./data/phase_3
#! panoptes_aggregation config /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-workflows.csv 22040 --min_version 0 --max_version 9.63 -d ./data/phase_3

# !mkdir ./data/phase_4
# ! panoptes_aggregation config /Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-workflows.csv 25351 -v 51.133 -d ./data/phase_4

## Have a look at the datasets

In [11]:
!tail /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv | grep workflow_translation_id

516322421,jenniferccguy,2484629,5df3221c2868fbefce6d,25379,Plastics GS dataset,15.25,2023-10-15 18:36:12 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T18:36:02.119Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T18:36:12.785Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":720,""clientHeight"":705,""naturalWidth"":1053,""naturalHeight"":1030}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380240"":{""retired"":{""id"":120701439,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:10:46.496Z"",""updated_at"":""2023-10-15T18:36:13.148Z"",""retired_at"":""2023-10-15T18:36:13.132Z"",""subject_id"":92380240,""retirement_reason"":""classification_count""},""Site"":""South Coast I"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCI01-2_144.jpg""}}",92380240
516323585,jenniferccguy,2484629,024a4098a4eceec7c129,25379,Plastics GS dataset,15.25,2023-10-15 18:44:56 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T18:36:12.808Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T18:44:56.122Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":670,""clientHeight"":705,""naturalWidth"":1405,""naturalHeight"":1478}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[{""x"":1246.9588623046875,""y"":1060.0660400390625,""tool"":1,""frame"":0,""details"":[],""tool_label"":""Plastic fishing gear""},{""x"":443.5546569824219,""y"":72.50151824951172,""tool"":2,""frame"":0,""details"":[{""value"":0}],""tool_label"":""Unknown/Other plastic object""},{""x"":334.1810607910156,""y"":798.6045532226562,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":1269.4642333984375,""y"":881.819091796875,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":781.3571166992188,""y"":920.4324951171875,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":870.0872192382812,""y"":1022.1088256835938,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":421.6154479980469,""y"":1153.548583984375,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":388.30572509765625,""y"":1111.153076171875,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":371.66314697265625,""y"":1127.946044921875,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":349.62847900390625,""y"":1126.5970458984375,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":269.4454040527344,""y"":1223.700439453125,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":143.45050048828125,""y"":1267.431640625,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":105.77967834472656,""y"":1265.1243896484375,""tool"":2,""frame"":0,""details"":[{""value"":0}],""tool_label"":""Unknown/Other plastic object""},{""x"":556.4821166992188,""y"":938.1968383789062,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":544.6864624023438,""y"":1224.5679931640625,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""}]}]","{""92380051"":{""retired"":{""id"":120701467,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:12:49.383Z"",""updated_at"":""2023-10-15T18:44:56.522Z"",""retired_at"":""2023-10-15T18:44:56.512Z"",""subject_id"":92380051,""retirement_reason"":""classification_count""},""Site"":""Gardner Islet"",""Island"":""Espa�ola"",""workflow"":""GS_plastics"",""Image_name"":""Esp_EGI02-2_67.jpg""}}",92380051
516324515,jenniferccguy,2484629,c19bf2d44c86008feb7d,25379,Plastics GS dataset,15.25,2023-10-15 18:53:53 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T18:44:56.137Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T18:53:52.995Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":735,""clientHeight"":705,""naturalWidth"":1085,""naturalHeight"":1040}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380214"":{""retired"":{""id"":120701483,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:13:24.157Z"",""updated_at"":""2023-10-15T18:53:53.279Z"",""retired_at"":""2023-10-15T18:53:53.268Z"",""subject_id"":92380214,""retirement_reason"":""classification_count""},""Site"":""South Coast A"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCA03-1_115.jpg""}}",92380214
516324685,jenniferccguy,2484629,d0ca723b9bfc65d3967b,25379,Plastics GS dataset,15.25,2023-10-15 18:55:03 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T18:53:53.020Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T18:55:03.742Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":720,""clientHeight"":705,""naturalWidth"":1053,""naturalHeight"":1031}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380219"":{""retired"":{""id"":120701480,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:13:09.306Z"",""updated_at"":""2023-10-15T18:55:04.111Z"",""retired_at"":""2023-10-15T18:55:04.098Z"",""subject_id"":92380219,""retirement_reason"":""classification_count""},""Site"":""South Coast I"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCI01-1_110.jpg""}}",92380219
516332536,jenniferccguy,2484629,c19bf2d44c86008feb7d,25379,Plastics GS dataset,15.25,2023-10-15 20:04:49 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T18:55:03.771Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:04:49.072Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":754,""clientHeight"":705,""naturalWidth"":1380,""naturalHeight"":1289}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[{""x"":560.0210571289062,""y"":103.38429260253906,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":731.0410766601562,""y"":291.5248107910156,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""}]}]","{""92380064"":{""retired"":{""id"":120701599,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:21:35.232Z"",""updated_at"":""2023-10-15T20:04:49.853Z"",""retired_at"":""2023-10-15T20:04:49.839Z"",""subject_id"":92380064,""retirement_reason"":""classification_count""},""Site"":""Gardner Islet"",""Island"":""Espa�ola"",""workflow"":""GS_plastics"",""Image_name"":""Esp_EGI03_40.jpg""}}",92380064
516332860,jenniferccguy,2484629,c3f08f61390431926f84,25379,Plastics GS dataset,15.25,2023-10-15 20:06:48 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T20:04:49.081Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:06:48.530Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":784,""clientHeight"":705,""naturalWidth"":1550,""naturalHeight"":1393}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[{""x"":626.6868286132812,""y"":1045.235107421875,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""},{""x"":547.821044921875,""y"":796.318115234375,""tool"":2,""frame"":0,""details"":[{""value"":0}],""tool_label"":""Unknown/Other plastic object""}]}]","{""92380073"":{""retired"":{""id"":120701516,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:15:46.063Z"",""updated_at"":""2023-10-15T20:06:49.085Z"",""retired_at"":""2023-10-15T20:06:49.074Z"",""subject_id"":92380073,""retirement_reason"":""classification_count""},""Site"":""Gardner Islet"",""Island"":""Espa�ola"",""workflow"":""GS_plastics"",""Image_name"":""Esp_EGI03-2-2_17.jpg""}}",92380073
516332910,jenniferccguy,2484629,c3f08f61390431926f84,25379,Plastics GS dataset,15.25,2023-10-15 20:07:02 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T20:06:48.540Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:07:02.636Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":720,""clientHeight"":705,""naturalWidth"":1053,""naturalHeight"":1030}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380220"":{""retired"":{""id"":120701437,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:10:37.400Z"",""updated_at"":""2023-10-15T20:07:03.103Z"",""retired_at"":""2023-10-15T20:07:03.091Z"",""subject_id"":92380220,""retirement_reason"":""classification_count""},""Site"":""South Coast I"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCI01-1_114.jpg""}}",92380220
516332992,jenniferccguy,2484629,c3f08f61390431926f84,25379,Plastics GS dataset,15.25,2023-10-15 20:07:28 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T20:07:02.645Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:07:28.784Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":722,""clientHeight"":705,""naturalWidth"":1412,""naturalHeight"":1378}],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T18:35:11.684Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[{""x"":941.1749267578125,""y"":1016.4962768554688,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Plastic bottle""}]}]","{""92380211"":{""retired"":{""id"":120701529,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:16:26.102Z"",""updated_at"":""2023-10-15T20:07:29.122Z"",""retired_at"":""2023-10-15T20:07:29.111Z"",""subject_id"":92380211,""retirement_reason"":""classification_count""},""Site"":""South Coast A"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCA02-2_68.jpg""}}",92380211
516332999,jenniferccguy,2484629,c3f08f61390431926f84,25379,Plastics GS dataset,15.25,2023-10-15 20:07:30 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T20:07:29.508Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:07:30.134Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[null],""subject_selection_state"":{""retired"":false,""selected_at"":""2023-10-15T20:07:29.447Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380121"":{""retired"":{""id"":120701506,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:15:37.547Z"",""updated_at"":""2023-10-15T20:07:30.538Z"",""retired_at"":""2023-10-15T20:07:30.521Z"",""subject_id"":92380121,""retirement_reason"":""classification_count""},""Site"":""South Coast B"",""Island"":""Espa�ola"",""workflow"":""GS_plastics"",""Image_name"":""Esp_ESCB-2.1-1_88.jpg""}}",92380121
516333044,jenniferccguy,2484629,c3f08f61390431926f84,25379,Plastics GS dataset,15.25,2023-10-15 20:07:46 UTC,,,"{""source"":""api"",""session"":""8327675098ea28ef4ed9f73d92d97a6af828eae69368ee3880c555e7ddfb0b10"",""viewport"":{""width"":1440,""height"":783},""started_at"":""2023-10-15T20:07:31.247Z"",""user_agent"":""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"",""utc_offset"":""-3600"",""finished_at"":""2023-10-15T20:07:46.132Z"",""seen_before"":true,""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":723,""clientHeight"":705,""naturalWidth"":1412,""naturalHeight"":1377}],""subject_selection_state"":{""retired"":true,""selected_at"":""2023-10-15T20:07:31.176Z"",""already_seen"":true,""selection_state"":""failover_fallback"",""finished_workflow"":false,""user_has_finished_workflow"":true},""workflow_translation_id"":""68195""}","[{""task"":""T4"",""task_label"":""Do you see any **plastic objects** in this photo? Please mark them all **in the middle**.  If you find other or unknown plastic object, please click Talk \u0026 Done. If you find FADs, classify them as fishing gear. Check the Field Guide and Help Text for help."",""value"":[]}]","{""92380209"":{""retired"":{""id"":120701469,""workflow_id"":25379,""classifications_count"":3,""created_at"":""2023-10-11T11:12:49.416Z"",""updated_at"":""2023-10-15T18:19:51.897Z"",""retired_at"":""2023-10-15T18:19:51.885Z"",""subject_id"":92380209,""retirement_reason"":""classification_count""},""Site"":""South Coast A"",""Island"":""Floreana"",""workflow"":""GS_plastics"",""Image_name"":""Flo_FSCA02-2_56.jpg""}}",92380209

In [12]:
!tail /Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv

570348141,Ekrouse,2169311,dc443c2a3eb398451a07,25351,Iguanas 4th launch,51.133,2024-06-30 19:32:11 UTC,,,"{""source"":""api"",""session"":""e7afd21d7e2fd8b501f25dfef7aaa452335325c66153fb356d495f73849b4904"",""viewport"":{""width"":1138,""height"":640},""started_at"":""2024-06-29T23:15:41.205Z"",""user_agent"":""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"",""utc_offset"":""14400"",""finished_at"":""2024-06-30T19:32:11.454Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":580,""clientHeight"":576,""naturalWidth"":719,""naturalHeight"":714}],""subject_selection_state"":{""retired"":false,""selected_at"":""2024-06-29T23:15:13.814Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68096""}","[{""task"":""T0"",""task_label"":""Do you see any **MARINE IGUANAS** in the photo? Follow a zigzag pattern when searching. You can zoom in and invert color if needed. Look carefully! Please select **Yes** only when you are sure.  Iguanas in this phase could be very pale. Check the Field Guide and the Help Text below for examples."",""value"":""Yes""},{""task"":""T2"",""task_label"":""Identify **MARINE IGUANAS** in this photo. Mark them all **in the head**! If you are not sure it is a **male** click **others**.  If iguanas are piled up, mark only those you are sure of. Check the Help Text and Field Guide for helpful examples."",""value"":[{""x"":624.771240234375,""y"":597.2889404296875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":592.0902709960938,""y"":605.56787109375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":545.8388671875,""y"":678.8958740234375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":465.78594970703125,""y"":563.7994995117188,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":705.260009765625,""y"":583.345458984375,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":571.796875,""y"":498.6882629394531,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":633.1749877929688,""y"":516.36669921875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":634.4821166992188,""y"":481.6323547363281,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":595.8251953125,""y"":434.57293701171875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":640.0846557617188,""y"":450.4461364746094,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":703.6414794921875,""y"":443.5366516113281,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":681.2937622070312,""y"":413.90667724609375,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":675.81591796875,""y"":340.8276672363281,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":643.2593383789062,""y"":371.2668762207031,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":655.5225219726562,""y"":322.9002685546875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":616.0562744140625,""y"":299.24609375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":540.3609008789062,""y"":337.4040222167969,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":544.5315551757812,""y"":280.13604736328125,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":585.7408447265625,""y"":278.0195617675781,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":653.841796875,""y"":270.798828125,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":597.3814086914062,""y"":245.65066528320312,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":631.6809692382812,""y"":220.93826293945312,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":716.9627685546875,""y"":267.6864318847656,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":708.4346313476562,""y"":226.72731018066406,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":716.1535034179688,""y"":200.52099609375,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":713.3523559570312,""y"":157.94342041015625,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":701.2136840820312,""y"":88.41255950927734,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":629.564453125,""y"":157.8811798095703,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":634.4199829101562,""y"":131.1768341064453,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":657.8880615234375,""y"":173.941162109375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":654.4019775390625,""y"":146.67654418945312,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":677.4343872070312,""y"":106.21543884277344,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":623.0906372070312,""y"":68.43098449707031,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":516.955078125,""y"":13.05826473236084,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":432.66925048828125,""y"":46.98336410522461,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":420.5305480957031,""y"":112.71710968017578,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":454.7677917480469,""y"":186.2318572998047,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":410.57061767578125,""y"":175.4629669189453,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":444.6833801269531,""y"":10.132622718811035,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":405.65289306640625,""y"":43.061744689941406,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":304.3106994628906,""y"":310.5409240722656,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":91.9775619506836,""y"":263.73046875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":149.931884765625,""y"":259.933349609375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":164.62277221679688,""y"":274.74835205078125,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":159.58055114746094,""y"":376.8348388671875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":217.7838592529297,""y"":357.226806640625,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":282.7101135253906,""y"":378.95123291015625,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":339.108154296875,""y"":390.40484619140625,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":390.46405029296875,""y"":413.9345703125,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":450.7215576171875,""y"":436.0948181152344,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":448.4183654785156,""y"":515.5853271484375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":283.76837158203125,""y"":579.576171875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":329.5217590332031,""y"":564.138671875,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":288.3748474121094,""y"":677.7411499023438,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":273.4349060058594,""y"":634.1052856445312,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":216.85011291503906,""y"":651.596923828125,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":417.6048278808594,""y"":675.2511596679688,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":437.08892822265625,""y"":695.41943359375,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":385.11053466796875,""y"":707.08203125,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":80.71041870117188,""y"":697.6825561523438,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":162.3817901611328,""y"":539.323974609375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":121.11035919189453,""y"":545.611083984375,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":94.21855926513672,""y"":545.7977905273438,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":18.834383010864258,""y"":659.0888671875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":46.84666442871094,""y"":657.2837524414062,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":52.635868072509766,""y"":617.0093383789062,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""},{""x"":210.2516632080078,""y"":449.2513122558594,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":137.23297119140625,""y"":425.78387451171875,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":117.37538146972656,""y"":411.59136962890625,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":30.350536346435547,""y"":227.46214294433594,""tool"":2,""frame"":0,""details"":[],""tool_label"":""Others (females, dark males, young males, juveniles)""},{""x"":5.824228286743164,""y"":586.5701904296875,""tool"":3,""frame"":0,""details"":[],""tool_label"":""Partial iguana""}]},{""task"":""T4"",""task_label"":""**Final Task.** Do you see **other species** or **plastic objects** in this photo? Please mark animals **in the head** and objects **in the middle**. Remember, for algae and plants just mark **once** if present. If you find something interesting not listed, please click Talk \u0026 Done. Check the Field Guide and Help Text for more information and examples."",""value"":[{""x"":200.78973388671875,""y"":61.2603759765625,""tool"":0,""frame"":0,""details"":[],""tool_label"":""Crab""}]}]","{""92458387"":{""retired"":{""id"":120750990,""workflow_id"":25351,""classifications_count"":21,""created_at"":""2023-10-12T17:01:36.243Z"",""updated_at"":""2024-06-30T02:39:21.067Z"",""retired_at"":""2024-06-30T02:39:21.055Z"",""subject_id"":92458387,""retirement_reason"":""classification_count""},""Site"":""Cabo Douglas"",""Island"":""Fernandina"",""Subset"":""Fer_CaboDouglas"",""Image_name"":""Fer_FCD01-02-03_20122021_22_18.jpg""}}",92458387
570348173,Ekrouse,2169311,dc443c2a3eb398451a07,25351,Iguanas 4th launch,51.133,2024-06-30 19:32:23 UTC,,,"{""source"":""api"",""session"":""e7afd21d7e2fd8b501f25dfef7aaa452335325c66153fb356d495f73849b4904"",""viewport"":{""width"":1138,""height"":640},""started_at"":""2024-06-30T19:32:11.506Z"",""user_agent"":""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"",""utc_offset"":""14400"",""finished_at"":""2024-06-30T19:32:23.772Z"",""live_project"":true,""interventions"":{""opt_in"":true,""messageShown"":false},""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":574,""clientHeight"":576,""naturalWidth"":711,""naturalHeight"":714}],""subject_selection_state"":{""retired"":false,""selected_at"":""2024-06-29T23:15:13.814Z"",""already_seen"":false,""selection_state"":""normal"",""finished_workflow"":false,""user_has_finished_workflow"":false},""workflow_translation_id"":""68096""}","[{""task"":""T0"",""task_label"":""Do you see any **MARINE IGUANAS** in the photo? Follow a zigzag pattern when searching. You can zoom in and invert color if needed. Look carefully! Please select **Yes** only when you are sure.  Iguanas in this phase could be very pale. Check the Field Guide and the Help Text below for examples."",""value"":""No""},{""task"":""T4"",""task_label"":""**Final Task.** Do you see **other species** or **plastic objects** in this photo? Please mark animals **in the head** and objects **in the middle**. Remember, for algae and plants just mark **once** if present. If you find something interesting not listed, please click Talk \u0026 Done. Check the Field Guide and Help Text for more information and examples."",""value"":[]}]","{""92468760"":{""retired"":{""id"":120746912,""workflow_id"":25351,""classifications_count"":21,""created_at"":""2023-10-12T16:35:09.220Z"",""updated_at"":""2024-06-30T08:47:43.848Z"",""retired_at"":""2024-06-30T08:47:43.839Z"",""subject_id"":92468760,""retirement_reason"":""classification_count""},""Site"":""Tintoreras"",""Island"":""Isabela"",""Subset"":""Isa_Tintoreras"",""Image_name"":""Isa_ISTI01-02-03_27012023_59_49.jpg""}}",92468760

## Extract the data

In [13]:
# phase 1
if data_folder == "./data/phase_1":
    !mkdir ./data/phase_1/V121.144
    !mkdir ./data/phase_1/V134.236
    
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_1/V121.144 ./data/phase_1/Extractor_config_workflow_14370_V121.144.yaml
    
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_1/V134.236 ./data/phase_1/Extractor_config_workflow_14370_V134.236-1.yaml
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

In [14]:
if data_folder == "./data/phase_2":
    # phase 2
    
    !mkdir ./data/phase_2/V89.162
    !mkdir ./data/phase_2/V93.166
    !mkdir ./data/phase_2/V94.166 
    
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_2/V89.162 ./data/phase_2/Extractor_config_workflow_20600_V89.162.yaml
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_2/V93.166 ./data/phase_2/Extractor_config_workflow_20600_V93.166.yaml
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_2/V94.166 ./data/phase_2/Extractor_config_workflow_20600_V94.166.yaml

else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

## Extacting data based on the classifications from 2023-10-15

In [15]:
if data_folder == "./data/phase_3":
    !mkdir ./data/phase_3/V7.63    
    !mkdir ./data/phase_3/V9.63

    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_3/V7.63 ./data/phase_3/Extractor_config_workflow_22040_V7.63.yaml
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2023-10-15/iguanas-from-above-classifications.csv -d ./data/phase_3/V9.63 ./data/phase_3/Extractor_config_workflow_22040_V9.63.yaml

else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

## Extacting data based on the newer classifications from 2024-08-08

In [16]:
if data_folder == "./data/phase_3":
    !mkdir ./data/phase_3/V7.63_08-08
    !mkdir ./data/phase_3/V9.63_08-08

    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv -d ./data/phase_3/V7.63_08-08 ./data/phase_3/Extractor_config_workflow_22040_V7.63.yaml
    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv -d ./data/phase_3/V9.63_08-08 ./data/phase_3/Extractor_config_workflow_22040_V9.63.yaml

else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

In [17]:
if data_folder == "./data/phase_4":
    !mkdir ./data/phase_4/V51.133    

    !panoptes_aggregation extract /Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv -d ./data/phase_4/V51.133 ./data/phase_4/Extractor_config_workflow_25351_V51.133.yaml


else:
    print(f"No data to process because of the data_folder: {data_folder}")

mkdir: ./data/phase_4/V51.133: File exists
/Users/christian/opt/anaconda3/envs/iguanas-from-above-zooniverse_310/lib/python3.10/site-packages/panoptes_aggregation/scripts/extract_panoptes_csv.py:68: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  classifications = pandas.read_csv(classification_csv_in, encoding='utf-8', dtype={'workflow_version': str})
Extracting: 100% |#############################################| Time:  0:00:49

### Merge the single point and questions extractions

In [18]:
# phase 1
if data_folder == "./data/phase_1":
    df_panoptes_point_extractor_1 = pd.read_csv(f"./data/phase_1/V121.144/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_2 = pd.read_csv(f"./data/phase_1/V134.236/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_1["workflow_version"] = "121.144"
    df_panoptes_point_extractor_2["workflow_version"] = "134.236"
    
    df_panoptes_question_1 = pd.read_csv(f"{data_folder}/V121.144/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_2 = pd.read_csv(f"{data_folder}/V134.236/question_extractor_extractions.csv", sep=",")
    
    df_panoptes_point_extractor = pd.concat([df_panoptes_point_extractor_1, df_panoptes_point_extractor_2], axis=0)
    df_panoptes_question = pd.concat([df_panoptes_question_1, df_panoptes_question_2], axis=0)
    
    df_panoptes_point_extractor
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

In [19]:
# # phase 2
if data_folder == "./data/phase_2":
    # read the rectangles annotations too there
    df_panotes_rectangle_extractor_1 = pd.read_csv(f"{data_folder}/V89.162/shape_extractor_rectangle_extractions.csv", sep=",")
    
    df_panoptes_point_extractor_1 = pd.read_csv(f"{data_folder}/V89.162/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_2 = pd.read_csv(f"{data_folder}/V93.166/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_3 = pd.read_csv(f"{data_folder}/V94.166/point_extractor_by_frame_extractions.csv", sep=",")
    
    df_panoptes_point_extractor_1["workflow_version"] = "89.162"
    df_panoptes_point_extractor_2["workflow_version"] = "93.166"
    df_panoptes_point_extractor_3["workflow_version"] = "94.166"
    
    df_panoptes_question_1 = pd.read_csv(f"{data_folder}/V89.162/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_2 = pd.read_csv(f"{data_folder}/V93.166/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_3 = pd.read_csv(f"{data_folder}/V94.166/question_extractor_extractions.csv", sep=",")
    
    df_panoptes_point_extractor = pd.concat([df_panoptes_point_extractor_1, df_panoptes_point_extractor_2, df_panoptes_point_extractor_3], axis=0)
    df_panoptes_question = pd.concat([df_panoptes_question_1, df_panoptes_question_2, df_panoptes_question_3], axis=0)

    df_panotes_rectangle_extractor_1
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

### phase 3 - 2023 data

In [20]:
if data_folder == "./data/phase_3":
    df_panoptes_point_extractor_1 = pd.read_csv(f"{data_folder}/V7.63/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_2 = pd.read_csv(f"{data_folder}/V9.63/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_1["workflow_version"] = "7.63"
    df_panoptes_point_extractor_2["workflow_version"] = "9.63"

    df_panoptes_question_1 = pd.read_csv(f"{data_folder}/V7.63/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_2 = pd.read_csv(f"{data_folder}/V9.63/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_1["workflow_version"] = "7.63"
    df_panoptes_question_2["workflow_version"] = "9.63"

    df_panoptes_point_extractor = pd.concat([df_panoptes_point_extractor_1, df_panoptes_point_extractor_2], axis=0)
    df_panoptes_question = pd.concat([df_panoptes_question_1, df_panoptes_question_2], axis=0)
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

NameError: name 'df_panoptes_point_extractor' is not defined

### phase 3 from  08-08-2024

In [22]:
if data_folder == "./data/phase_3":
    df_panoptes_point_extractor_1 = pd.read_csv(f"{data_folder}/V7.63_08-08/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_2 = pd.read_csv(f"{data_folder}/V9.63_08-08/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_1["workflow_version"] = "7.63"
    df_panoptes_point_extractor_2["workflow_version"] = "9.63"

    df_panoptes_question_1 = pd.read_csv(f"{data_folder}/V7.63_08-08/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_2 = pd.read_csv(f"{data_folder}/V7.63_08-08/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_1["workflow_version"] = "7.63"
    df_panoptes_question_2["workflow_version"] = "9.63"

    df_panoptes_point_extractor = pd.concat([df_panoptes_point_extractor_1, df_panoptes_point_extractor_2], axis=0)
    df_panoptes_question = pd.concat([df_panoptes_question_1, df_panoptes_question_2], axis=0)
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

No data to process because of the data_folder: ./data/phase_4

## Phase 4

In [23]:
# phase 4
if data_folder == "./data/phase_4":
    df_panoptes_point_extractor_1 = pd.read_csv(f"{data_folder}/V51.133/point_extractor_by_frame_extractions.csv", sep=",")
    df_panoptes_point_extractor_1["workflow_version"] = "51.133"

    df_panoptes_question_1 = pd.read_csv(f"{data_folder}/V51.133/question_extractor_extractions.csv", sep=",")
    df_panoptes_question_1["workflow_version"] = "51.133"

    df_panoptes_point_extractor = pd.concat([df_panoptes_point_extractor_1], axis=0)
    df_panoptes_question = pd.concat([df_panoptes_question_1], axis=0)
    
else:
    print(f"No data to process because of the data_folder: {data_folder}")

In [24]:
df_panoptes_point_extractor.drop(columns=["user_name", "user_id"], inplace=False)

,classification_id,workflow_id,task,created_at,subject_id,extractor,data.aggregation_version,data.frame0.T2_tool2_x,data.frame0.T2_tool2_y,data.frame0.T4_tool1_x,...,data.frame0.T4_tool6_y,data.frame0.T4_tool8_x,data.frame0.T4_tool8_y,data.frame0.T2_tool3_x,data.frame0.T2_tool3_y,data.frame0.T2_tool1_x,data.frame0.T2_tool1_y,data.frame0.T4_tool3_x,data.frame0.T4_tool3_y,workflow_version
0,516391010,25351,T2,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,[509.775390625],[664.4249267578125],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
1,516391010,25351,T4,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,NaN,[470.683349609375],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
2,516403493,25351,T2,2023-10-16 12:34:09 UTC,92464036,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
3,516403493,25351,T4,2023-10-16 12:34:09 UTC,92464036,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
4,516403739,25351,T2,2023-10-16 12:36:25 UTC,92464442,point_extractor_by_frame,4.1.0,"[571.8541870117188, 679.4479370117188, 591.519...","[126.17318725585938, 71.54948425292969, 22.937...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404635,570813276,25351,T4,2024-07-03 09:38:38 UTC,92461607,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404636,570813416,25351,T2,2024-07-03 09:40:06 UTC,92458660,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404637,570813416,25351,T4,2024-07-03 09:40:06 UTC,92458660,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404638,570813530,25351,T2,2024-07-03 09:41:28 UTC,92460485,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404639,570813530,25351,T4,2024-07-03 09:41:28 UTC,92460485,point_extractor_by_frame,4.1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133

In [25]:
df_panoptes_point_extractor.sort_values(by=[ "created_at"], ascending=False)

,classification_id,user_name,user_id,workflow_id,task,created_at,subject_id,extractor,data.aggregation_version,data.frame0.T2_tool2_x,...,data.frame0.T4_tool6_y,data.frame0.T4_tool8_x,data.frame0.T4_tool8_y,data.frame0.T2_tool3_x,data.frame0.T2_tool3_y,data.frame0.T2_tool1_x,data.frame0.T2_tool1_y,data.frame0.T4_tool3_x,data.frame0.T4_tool3_y,workflow_version
404639,570813530,Ramalina,2606938.0,25351,T4,2024-07-03 09:41:28 UTC,92460485,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404638,570813530,Ramalina,2606938.0,25351,T2,2024-07-03 09:41:28 UTC,92460485,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404637,570813416,Ramalina,2606938.0,25351,T4,2024-07-03 09:40:06 UTC,92458660,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404636,570813416,Ramalina,2606938.0,25351,T2,2024-07-03 09:40:06 UTC,92458660,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
404635,570813276,Ramalina,2606938.0,25351,T4,2024-07-03 09:38:38 UTC,92461607,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,516403739,ANDREAVARELA89,1983945.0,25351,T4,2023-10-16 12:36:25 UTC,92464442,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
2,516403493,ANDREAVARELA89,1983945.0,25351,T2,2023-10-16 12:34:09 UTC,92464036,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
3,516403493,ANDREAVARELA89,1983945.0,25351,T4,2023-10-16 12:34:09 UTC,92464036,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
1,516391010,ANDREAVARELA89,1983945.0,25351,T4,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133
0,516391010,ANDREAVARELA89,1983945.0,25351,T2,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,[509.775390625],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133

## Merge the subjects file with the point extractor file to get the image name
This is necessary to get the image name for the points.

In [26]:
# join the image name from the subjects file
df_panoptes_point_extractor = df_panoptes_point_extractor.merge(df_subjects[["subject_id", "image_name"]], left_on="subject_id", right_on="subject_id")
df_panoptes_point_extractor = df_panoptes_point_extractor[df_panoptes_point_extractor.subject_id.isin(df_subjects.subject_id)]

df_panoptes_point_extractor

,classification_id,user_name,user_id,workflow_id,task,created_at,subject_id,extractor,data.aggregation_version,data.frame0.T2_tool2_x,...,data.frame0.T4_tool8_x,data.frame0.T4_tool8_y,data.frame0.T2_tool3_x,data.frame0.T2_tool3_y,data.frame0.T2_tool1_x,data.frame0.T2_tool1_y,data.frame0.T4_tool3_x,data.frame0.T4_tool3_y,workflow_version,image_name
0,516391010,ANDREAVARELA89,1983945.0,25351,T2,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,[509.775390625],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
1,516391010,ANDREAVARELA89,1983945.0,25351,T4,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
2,520603679,Kanesh-Gandhi,2644392.0,25351,T2,2023-11-05 18:25:57 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
3,520603679,Kanesh-Gandhi,2644392.0,25351,T4,2023-11-05 18:25:57 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
4,523311597,katilling,2678358.0,25351,T2,2023-11-18 02:33:13 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,[508.81048583984375],[665.7697143554688],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404635,569258394,thermomole,2701687.0,25351,T4,2024-06-24 12:16:33 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404636,569377745,BirdLeaf,1734449.0,25351,T2,2024-06-24 23:40:00 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404637,569377745,BirdLeaf,1734449.0,25351,T4,2024-06-24 23:40:00 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404638,569672478,Siddharth1,1836105.0,25351,T2,2024-06-26 18:47:01 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404639,569672478,Siddharth1,1836105.0,25351,T4,2024-06-26 18:47:01 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg

## Anonymise the data

In [27]:
from hashlib import blake2b

df_panoptes_point_extractor["user_id"] = df_panoptes_point_extractor['user_id'].apply(lambda x: blake2b(str(x).encode(), digest_size=16).hexdigest() if not pd.isnull(x) else x)
# Anonymize 'user_name' by hashing
df_panoptes_point_extractor['user_name'] = df_panoptes_point_extractor['user_name'].apply(lambda x: blake2b(x.encode(), digest_size=16).hexdigest() if isinstance(x, str) else x)

df_panoptes_question["user_id"] = df_panoptes_question['user_id'].apply(lambda x: blake2b(str(x).encode(), digest_size=16).hexdigest() if not pd.isnull(x) else x)
# Anonymize 'user_name' by hashing
df_panoptes_question['user_name'] = df_panoptes_question['user_name'].apply(lambda x: blake2b(x.encode(), digest_size=16).hexdigest() if isinstance(x, str) else x)

In [28]:
df_panoptes_question[df_panoptes_question["data.yes"] == 1.0].groupby("subject_id").size().sort_values(ascending=False)

subject_id
92462183    38
92463214    28
92459074    26
92463918    24
92458601    24
            ..
92464574     1
92460502     1
92464578     1
92460495     1
92459960     1
Length: 6145, dtype: int64

## Determine the amount of yes Answers for "Is there an Iguana"

In [29]:
df_panoptes_question

,classification_id,user_name,user_id,workflow_id,task,created_at,subject_id,extractor,data.yes,data.aggregation_version,data.no,workflow_version
0,516391010,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,T0,2023-10-16 10:10:44 UTC,92462758,question_extractor,1.0,4.1.0,NaN,51.133
1,516403493,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,T0,2023-10-16 12:34:09 UTC,92464036,question_extractor,NaN,4.1.0,1.0,51.133
2,516403739,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,T0,2023-10-16 12:36:25 UTC,92464442,question_extractor,1.0,4.1.0,NaN,51.133
3,516405060,d2618fb74db893e8bb165cb30a48416d,NaN,25351,T0,2023-10-16 12:49:03 UTC,92462615,question_extractor,NaN,4.1.0,1.0,51.133
4,516405305,0718143716f54f03e5311b0d801830ef,NaN,25351,T0,2023-10-16 12:51:11 UTC,92459041,question_extractor,1.0,4.1.0,NaN,51.133
...,...,...,...,...,...,...,...,...,...,...,...,...
202315,570813037,1243c157ab8b76cc35166a4fe97a6f91,676a88d0e03d10c46bdea529074f09f0,25351,T0,2024-07-03 09:36:00 UTC,92460149,question_extractor,NaN,4.1.0,1.0,51.133
202316,570813145,1243c157ab8b76cc35166a4fe97a6f91,676a88d0e03d10c46bdea529074f09f0,25351,T0,2024-07-03 09:36:57 UTC,92463653,question_extractor,NaN,4.1.0,1.0,51.133
202317,570813276,1243c157ab8b76cc35166a4fe97a6f91,676a88d0e03d10c46bdea529074f09f0,25351,T0,2024-07-03 09:38:38 UTC,92461607,question_extractor,NaN,4.1.0,1.0,51.133
202318,570813416,1243c157ab8b76cc35166a4fe97a6f91,676a88d0e03d10c46bdea529074f09f0,25351,T0,2024-07-03 09:40:06 UTC,92458660,question_extractor,NaN,4.1.0,1.0,51.133
202319,570813530,1243c157ab8b76cc35166a4fe97a6f91,676a88d0e03d10c46bdea529074f09f0,25351,T0,2024-07-03 09:41:28 UTC,92460485,question_extractor,NaN,4.1.0,1.0,51.133

In [30]:
df_panoptes_question_r = df_panoptes_question[df_panoptes_question.task == "T0"][["subject_id", "data.no", "data.yes"]].groupby("subject_id").sum()

df_panoptes_question_r = df_panoptes_question_r.reset_index()
df_panoptes_question_r = df_panoptes_question_r[df_panoptes_question_r.subject_id.isin(df_subjects.subject_id)]
df_panoptes_question_r

      subject_id  data.no  data.yes
0       92458387      0.0      22.0
1       92458388      4.0      16.0
2       92458389      3.0      17.0
3       92458390      1.0      19.0
4       92458391     21.0       0.0
...          ...      ...       ...
9923    92469731      9.0      11.0
9924    92469733      0.0      20.0
9925    92469734      1.0      19.0
9926    92469735     20.0       0.0
9927    92469736     21.0       0.0

[9928 rows x 3 columns]

In [31]:
df_panoptes_question_r.to_csv(output_path / config["panoptes_question"], index = False)

## Get the Point Marks Analysis Ready

Filter for T2 only

In [32]:
df_panoptes_point_extractor_r = df_panoptes_point_extractor[
    (df_panoptes_point_extractor.task == "T2")
]
df_panoptes_point_extractor_r.columns

Index(['classification_id', 'user_name', 'user_id', 'workflow_id', 'task',
       'created_at', 'subject_id', 'extractor', 'data.aggregation_version',
       'data.frame0.T2_tool2_x', 'data.frame0.T2_tool2_y',
       'data.frame0.T4_tool1_x', 'data.frame0.T4_tool1_y',
       'data.frame0.T4_tool4_x', 'data.frame0.T4_tool4_y',
       'data.frame0.T4_tool0_x', 'data.frame0.T4_tool0_y',
       'data.frame0.T4_tool2_x', 'data.frame0.T4_tool2_y',
       'data.frame0.T2_tool0_x', 'data.frame0.T2_tool0_y',
       'data.frame0.T4_tool5_x', 'data.frame0.T4_tool5_y',
       'data.frame0.T4_tool7_x', 'data.frame0.T4_tool7_y',
       'data.frame0.T4_tool6_x', 'data.frame0.T4_tool6_y',
       'data.frame0.T4_tool8_x', 'data.frame0.T4_tool8_y',
       'data.frame0.T2_tool3_x', 'data.frame0.T2_tool3_y',
       'data.frame0.T2_tool1_x', 'data.frame0.T2_tool1_y',
       'data.frame0.T4_tool3_x', 'data.frame0.T4_tool3_y', 'workflow_version',
       'image_name'],
      dtype='object')

### Which tool is which now?
| Tool Name               | Classification                               |
|-------------------------|----------------------------------------------|
| data.frame0.T2_tool0_x  | Adult Male in a lek                          |
| data.frame0.T2_tool1_x  | Adult Male alone                             |
| data.frame0.T2_tool2_x  | Others (females, young males, juveniles)     |
| data.frame0.T2_tool3_x  | Partial iguana                               |
| data.frame0.T2_tool4_x  | Could be an iguana, not sure                 |

Is "Could be an iguana, not sure" and "Partial Iguana" are omitted.

In [33]:
df_panoptes_point_extractor_r

,classification_id,user_name,user_id,workflow_id,task,created_at,subject_id,extractor,data.aggregation_version,data.frame0.T2_tool2_x,...,data.frame0.T4_tool8_x,data.frame0.T4_tool8_y,data.frame0.T2_tool3_x,data.frame0.T2_tool3_y,data.frame0.T2_tool1_x,data.frame0.T2_tool1_y,data.frame0.T4_tool3_x,data.frame0.T4_tool3_y,workflow_version,image_name
0,516391010,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,T2,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,[509.775390625],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
2,520603679,3e5c95da2f84e6f04e971408dbdab8d7,1ed243d8863f93f280b5aecce0c2f80c,25351,T2,2023-11-05 18:25:57 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
4,523311597,83dd7d12ba62f69e40d9bd8b5eeb23b0,dab35ca4005258caceaab79f37e23712,25351,T2,2023-11-18 02:33:13 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,[508.81048583984375],[665.7697143554688],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
6,528076882,5b7f6cd059096be78a76988c60f1c741,NaN,25351,T2,2023-12-09 19:12:49 UTC,92462758,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,[509.3125],[663.75],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
8,529018098,386fa01a49140278f5494d0042b9f20a,27a60a267e4e0f1d976cac30038e8fe3,25351,T2,2023-12-14 04:32:06 UTC,92462758,point_extractor_by_frame,4.1.0,[509.70989990234375],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404630,566921121,dce9e8bb730153bf0d0bad3f52b853e0,b0e10539db360fb487870c2b5dff8aaa,25351,T2,2024-06-11 15:39:30 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404632,567651844,940c519bb3437ec73a4fc6071eae5041,8e606b31ff94fd9d6ba2151bb5d1d030,25351,T2,2024-06-15 09:53:39 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404634,569258394,ba42128d23c5d1e18111062e13f8c2d3,00b4196b5d562fbd25d0585353c627f9,25351,T2,2024-06-24 12:16:33 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404636,569377745,17d2b0a53f67a0ccba57a9b0aec20f50,92c6091eaf50a7f1019c6cd81f8dd5e4,25351,T2,2024-06-24 23:40:00 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg
404638,569672478,d7a23387a21ddc0e9967c9ef6975bd39,e6790fd8a39041dd4cbc65d0220ba994,25351,T2,2024-06-26 18:47:01 UTC,92469395,point_extractor_by_frame,4.1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg

In [34]:
# create a flat structure from the nested marks over multiple columns from that.
from ast import literal_eval

expected_columns = {'data.frame0.T2_tool0_x', 'data.frame0.T2_tool1_x', 'data.frame0.T2_tool2_x', 'data.frame0.T2_tool0_y', 'data.frame0.T2_tool1_y', 'data.frame0.T2_tool2_y'}
assert expected_columns.issubset(df_panoptes_point_extractor_r.columns), f"Missing columns: {expected_columns - set(df_panoptes_point_extractor_r.columns)}" 

# In phase 3 Tool 4 does not exist
if data_folder == "./data/phase_3" or data_folder == "./data/phase_4": 
    columns_keep_x = ['data.frame0.T2_tool0_x', 'data.frame0.T2_tool1_x', 'data.frame0.T2_tool2_x']
    columns_keep_y = ['data.frame0.T2_tool0_y', 'data.frame0.T2_tool1_y', 'data.frame0.T2_tool2_y']


else:
    expected_columns = expected_columns + {'data.frame0.T2_tool4_x', 'data.frame0.T2_tool4_y'}
    assert expected_columns.issubset(df_panoptes_point_extractor_r.columns), f"Missing columns: {expected_columns - set(df_panoptes_point_extractor_r.columns)}" 
    columns_keep_x = ['data.frame0.T2_tool0_x', 'data.frame0.T2_tool1_x', 'data.frame0.T2_tool2_x', 'data.frame0.T2_tool4_x']
    columns_keep_y = ['data.frame0.T2_tool0_y', 'data.frame0.T2_tool1_y', 'data.frame0.T2_tool2_y', 'data.frame0.T2_tool4_y']

for col in columns_keep_x + columns_keep_y:
    df_panoptes_point_extractor_r[col] = df_panoptes_point_extractor_r[col].apply(lambda x: literal_eval(x) if pd.notnull(x) else [])

# Merge the lists in 'x' and 'y' coordinates
df_panoptes_point_extractor_r['x'] = df_panoptes_point_extractor_r[columns_keep_x].values.tolist()
df_panoptes_point_extractor_r['y'] = df_panoptes_point_extractor_r[columns_keep_y].values.tolist()

# Flatten the lists in each row for 'x' and 'y'
df_panoptes_point_extractor_r['x'] = df_panoptes_point_extractor_r['x'].apply(lambda x: [item for sublist in x for item in sublist])
df_panoptes_point_extractor_r['y'] = df_panoptes_point_extractor_r['y'].apply(lambda x: [item for sublist in x for item in sublist])

# Explode the DataFrame to separate rows for each x, y pair
# Explode the DataFrame based on these columns to get separate rows for each list element
df_panoptes_point_extractor_r

/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/ipykernel_31256/3361256823.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panoptes_point_extractor_r[col] = df_panoptes_point_extractor_r[col].apply(lambda x: literal_eval(x) if pd.notnull(x) else [])
/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/ipykernel_31256/3361256823.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panoptes_point_extractor_r['x'] = df_panoptes_point_extractor_r[columns_keep_x].values.tolist()
/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/ipykernel_31256/3361256823.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panoptes_point_extractor_r['y'] = df_panoptes_point_extractor_r[columns_keep_y].values.tolist()
/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/ipykernel_31256/3361256823.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panoptes_point_extractor_r['x'] = df_panoptes_point_extractor_r['x'].apply(lambda x: [item for sublist in x for item in sublist])
/var/folders/2k/78nn7s4548986wsjh29rhj9w0000gn/T/ipykernel_31256/3361256823.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_panoptes_point_extractor_r['y'] = df_panoptes_point_extractor_r['y'].apply(lambda x: [item for sublist in x for item in sublist])

,classification_id,user_name,user_id,workflow_id,task,created_at,subject_id,extractor,data.aggregation_version,data.frame0.T2_tool2_x,...,data.frame0.T2_tool3_x,data.frame0.T2_tool3_y,data.frame0.T2_tool1_x,data.frame0.T2_tool1_y,data.frame0.T4_tool3_x,data.frame0.T4_tool3_y,workflow_version,image_name,x,y
0,516391010,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,T2,2023-10-16 10:10:44 UTC,92462758,point_extractor_by_frame,4.1.0,[509.775390625],...,NaN,NaN,[],[],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg,[509.775390625],[664.4249267578125]
2,520603679,3e5c95da2f84e6f04e971408dbdab8d7,1ed243d8863f93f280b5aecce0c2f80c,25351,T2,2023-11-05 18:25:57 UTC,92462758,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg,[486.3125],[679.75]
4,523311597,83dd7d12ba62f69e40d9bd8b5eeb23b0,dab35ca4005258caceaab79f37e23712,25351,T2,2023-11-18 02:33:13 UTC,92462758,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[508.81048583984375],[665.7697143554688],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg,[508.81048583984375],[665.7697143554688]
6,528076882,5b7f6cd059096be78a76988c60f1c741,NaN,25351,T2,2023-12-09 19:12:49 UTC,92462758,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[509.3125],[663.75],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg,[509.3125],[663.75]
8,529018098,386fa01a49140278f5494d0042b9f20a,27a60a267e4e0f1d976cac30038e8fe3,25351,T2,2023-12-14 04:32:06 UTC,92462758,point_extractor_by_frame,4.1.0,[509.70989990234375],...,NaN,NaN,[],[],NaN,NaN,51.133,Fer_FPE03-04-05_18122021_118_14.jpg,[509.70989990234375],[666.1571044921875]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404630,566921121,dce9e8bb730153bf0d0bad3f52b853e0,b0e10539db360fb487870c2b5dff8aaa,25351,T2,2024-06-11 15:39:30 UTC,92469395,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg,[],[]
404632,567651844,940c519bb3437ec73a4fc6071eae5041,8e606b31ff94fd9d6ba2151bb5d1d030,25351,T2,2024-06-15 09:53:39 UTC,92469395,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg,[],[]
404634,569258394,ba42128d23c5d1e18111062e13f8c2d3,00b4196b5d562fbd25d0585353c627f9,25351,T2,2024-06-24 12:16:33 UTC,92469395,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg,[],[]
404636,569377745,17d2b0a53f67a0ccba57a9b0aec20f50,92c6091eaf50a7f1019c6cd81f8dd5e4,25351,T2,2024-06-24 23:40:00 UTC,92469395,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg,[],[]
404638,569672478,d7a23387a21ddc0e9967c9ef6975bd39,e6790fd8a39041dd4cbc65d0220ba994,25351,T2,2024-06-26 18:47:01 UTC,92469395,point_extractor_by_frame,4.1.0,[],...,NaN,NaN,[],[],NaN,NaN,51.133,Isa_ISVB01_27012023_57_29.jpg,[],[]

In [35]:
df_panoptes_point_extractor_r = df_panoptes_point_extractor_r[
    ['classification_id', 'user_name', 'user_id', 'workflow_id',  'workflow_version', 'task',
     'created_at', 'subject_id', "image_name",
     'x', 'y'
     ]].reset_index(drop=True)

df_panoptes_point_extractor_r

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y
0,516391010,386fc0ec047b7e259744e72e8e64b9f9,ea57b1088a10fa7fef30ed0b344e2ca3,25351,51.133,T2,2023-10-16 10:10:44 UTC,92462758,Fer_FPE03-04-05_18122021_118_14.jpg,[509.775390625],[664.4249267578125]
1,520603679,3e5c95da2f84e6f04e971408dbdab8d7,1ed243d8863f93f280b5aecce0c2f80c,25351,51.133,T2,2023-11-05 18:25:57 UTC,92462758,Fer_FPE03-04-05_18122021_118_14.jpg,[486.3125],[679.75]
2,523311597,83dd7d12ba62f69e40d9bd8b5eeb23b0,dab35ca4005258caceaab79f37e23712,25351,51.133,T2,2023-11-18 02:33:13 UTC,92462758,Fer_FPE03-04-05_18122021_118_14.jpg,[508.81048583984375],[665.7697143554688]
3,528076882,5b7f6cd059096be78a76988c60f1c741,NaN,25351,51.133,T2,2023-12-09 19:12:49 UTC,92462758,Fer_FPE03-04-05_18122021_118_14.jpg,[509.3125],[663.75]
4,529018098,386fa01a49140278f5494d0042b9f20a,27a60a267e4e0f1d976cac30038e8fe3,25351,51.133,T2,2023-12-14 04:32:06 UTC,92462758,Fer_FPE03-04-05_18122021_118_14.jpg,[509.70989990234375],[666.1571044921875]
...,...,...,...,...,...,...,...,...,...,...,...
202315,566921121,dce9e8bb730153bf0d0bad3f52b853e0,b0e10539db360fb487870c2b5dff8aaa,25351,51.133,T2,2024-06-11 15:39:30 UTC,92469395,Isa_ISVB01_27012023_57_29.jpg,[],[]
202316,567651844,940c519bb3437ec73a4fc6071eae5041,8e606b31ff94fd9d6ba2151bb5d1d030,25351,51.133,T2,2024-06-15 09:53:39 UTC,92469395,Isa_ISVB01_27012023_57_29.jpg,[],[]
202317,569258394,ba42128d23c5d1e18111062e13f8c2d3,00b4196b5d562fbd25d0585353c627f9,25351,51.133,T2,2024-06-24 12:16:33 UTC,92469395,Isa_ISVB01_27012023_57_29.jpg,[],[]
202318,569377745,17d2b0a53f67a0ccba57a9b0aec20f50,92c6091eaf50a7f1019c6cd81f8dd5e4,25351,51.133,T2,2024-06-24 23:40:00 UTC,92469395,Isa_ISVB01_27012023_57_29.jpg,[],[]
202319,569672478,d7a23387a21ddc0e9967c9ef6975bd39,e6790fd8a39041dd4cbc65d0220ba994,25351,51.133,T2,2024-06-26 18:47:01 UTC,92469395,Isa_ISVB01_27012023_57_29.jpg,[],[]

In [36]:
# explode the lists of marks per user into one row per mark
df_panoptes_point_extractor_r_ex = df_panoptes_point_extractor_r.apply(lambda x: x.explode() if x.name in ['x', 'y'] else x)

In [37]:
# images with no marks have NaN values in the 'merged_x' and 'merged_y' columns
df_panoptes_point_extractor_r_ex_dropped = df_panoptes_point_extractor_r_ex.dropna(subset=['x', 'y'], how='all').sort_values(by=['user_id', 'subject_id', 'task', 'created_at'])
df_panoptes_point_extractor_r_ex_dropped

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y
137313,525501702,2c71cd336686d99b2fddf9bf5c5e2d86,0013808b3d09505e4e150c365ee48a43,25351,51.133,T2,2023-11-29 02:20:34 UTC,92466390,Isa_ISCWN02_18012023_81_36.jpg,335.898926,655.554871
199593,537681646,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:15:54 UTC,92461153,Fer_FPE01-06_18122021_32_33.jpg,16.868912,245.235474
87112,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,652.825562,596.568848
87112,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,233.017883,561.024475
111210,537681792,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:16:38 UTC,92465107,Fer_FPM01-02_20012023_52_74.jpg,67.784637,594.647522
...,...,...,...,...,...,...,...,...,...,...,...
44075,563671982,ff34a702faa50d4664aaa32e1f4aa569,NaN,25351,51.133,T2,2024-05-24 17:24:30 UTC,92469726,Isa_ISVB01_27012023_75_37.jpg,349.43692,122.996864
76393,518717765,9b7e5901c61869dc6c15ef440db39903,NaN,25351,51.133,T2,2023-10-26 22:26:33 UTC,92469727,Isa_ISVB02_27012023_154.jpg,456.804688,129.300003
73028,518469002,1d23a3d52d2335e30eda5f7fd35beb05,NaN,25351,51.133,T2,2023-10-26 01:01:00 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,582.7146,657.208252
73035,535441276,b6254211ad7527a1e3d29e0d8ba29660,NaN,25351,51.133,T2,2024-01-18 22:56:05 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,599.316406,675.324341
63946,518215148,57c0288002e097cae09fb1178cba0ba2,NaN,25351,51.133,T2,2023-10-24 22:09:30 UTC,92469734,Isa_ISVB01_27012023_27_16.jpg,230.3125,590.421875

In [38]:
# cast x and y to int
df_panoptes_point_extractor_r_ex_dropped = df_panoptes_point_extractor_r_ex_dropped.astype({'x': 'int32', 'y': 'int32'})
df_panoptes_point_extractor_r_ex_dropped

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y
137313,525501702,2c71cd336686d99b2fddf9bf5c5e2d86,0013808b3d09505e4e150c365ee48a43,25351,51.133,T2,2023-11-29 02:20:34 UTC,92466390,Isa_ISCWN02_18012023_81_36.jpg,335,655
199593,537681646,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:15:54 UTC,92461153,Fer_FPE01-06_18122021_32_33.jpg,16,245
87112,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,652,596
87112,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,233,561
111210,537681792,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:16:38 UTC,92465107,Fer_FPM01-02_20012023_52_74.jpg,67,594
...,...,...,...,...,...,...,...,...,...,...,...
44075,563671982,ff34a702faa50d4664aaa32e1f4aa569,NaN,25351,51.133,T2,2024-05-24 17:24:30 UTC,92469726,Isa_ISVB01_27012023_75_37.jpg,349,122
76393,518717765,9b7e5901c61869dc6c15ef440db39903,NaN,25351,51.133,T2,2023-10-26 22:26:33 UTC,92469727,Isa_ISVB02_27012023_154.jpg,456,129
73028,518469002,1d23a3d52d2335e30eda5f7fd35beb05,NaN,25351,51.133,T2,2023-10-26 01:01:00 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,582,657
73035,535441276,b6254211ad7527a1e3d29e0d8ba29660,NaN,25351,51.133,T2,2024-01-18 22:56:05 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,599,675
63946,518215148,57c0288002e097cae09fb1178cba0ba2,NaN,25351,51.133,T2,2023-10-24 22:09:30 UTC,92469734,Isa_ISVB01_27012023_27_16.jpg,230,590

In [39]:
print(f"write file to: {config['flat_panoptes_points']}")
df_panoptes_point_extractor_r_ex_dropped.to_csv(config["flat_panoptes_points"], sep=",", index = False)

write file to: /Users/christian/data/zooniverse/2024_09_25_analysis/Iguanas 4th launch/flat_panoptes_points_Iguanas 4th launch.csv

## Inspecting the results
Check the numbers for a single subject_id

In [ ]:
### Looks the images in question

subject_id_2 = 72373250 
df_debug = df_panoptes_point_extractor_r_ex_dropped[(df_panoptes_point_extractor_r_ex_dropped.subject_id == subject_id_2)]
df_debug

In [ ]:
df_debug.groupby('user_name').size()

In [ ]:
df_debug[df_debug.user_name == "CallieSanDiego"]

## Download images
iguanas-from-above-subjects_with_url.csv will be used to track which url was already downlaoded.

In [ ]:
## save the file the extra columns we need for downloading.
df_subjects.to_csv(output_path / "iguanas-from-above-subjects_with_url.csv")


# read the modified csv
df_subjects = pd.read_csv(output_path / "iguanas-from-above-subjects_with_url.csv")

In [ ]:
# df_subjects = pd.read_csv(output_path / "iguanas-from-above-subjects_with_url.csv")

# downoaded_images_path = Path("./data/downloaded_images")
# downoaded_images_path.mkdir(exist_ok=True, parents=True)
# return_val = True
# # df = df_subjects[df_subjects.subject_id.isin([44660616, 47968406])]
# # df = df_subjects[df_subjects.subject_id.isin([44660616, 47968406])]
# for index, row in df_subjects[df_subjects.workflow_id.isin([workflow_id_p1])].iterrows():
#     # Only download if necessary
#     if pd.isna(row.get("filepath")) or not row.get("filepath", False):
#         flight_code = row['flight_code']
#         url = row['url']
#         image_name = Path(row['image_name']).name
#         # Extract the filename from the URL and create a unique name using index
#         filename = downoaded_images_path.joinpath(f"{image_name}_{row['subject_id']}_{flight_code}.jpeg")
#         df_subjects.loc[index, 'filepath'] = filename
#         # Download the image
#         return_val = download_image(url, filename)
# 
#         # print(f"Downloaded {filename}")
#     if return_val == False:
#         print("there was a problem")
#         # break

In [ ]:
df_subjects.to_csv(output_path / "iguanas-from-above-subjects_with_url.csv")