# Clustering Zooniverse Marks to count Iguanas
Count all the iguanas in the images by clustering the marks from the zooniverse volunteers.
This does not compare the results to the gold standard and requires only a single file, the flattened zooniverse data export.

In [1]:
%load_ext autoreload
%autoreload 2

import sys

sys.path.append("./")
sys.path.append("./zooniverse")

## Intro
### Retrieve a Classification report from Zooniverse
This notebook is used to cluster the marks from the zooniverse volunteers to count the iguanas in the images saved in results/<phase_tag>/flat_dataset_filtered_Iguanas 3rd launch.csv

Used Methods are:

### DBSCAN 
It does not require the number of clusters to be specified. It is used here because, but has min_samples and eps as hyperparameters which need to be found. [Link](https://scikit-learn.org/stable/auto_examples/cluster/plot_dbscan.html)
For finding eps and min_sample a simple **grid search** is used.
Additionally, DBSCAN not assume a specific shape for the clusters (K-means assumes clusters are gaussian in shape) even though we should assume that points around an iguana is gaussian shaped.

### HDBSCAN
It is an extension of DBSCAN which is more robust to hyperparameter settings as it finds epsilon and min_samples automatically. [Link](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html)

## Load the data

In [7]:
from pathlib import Path

import pandas as pd
from zooniverse.analysis import get_annotation_count_stats
from zooniverse.utils.filters import filter_df_user_threshold



# Phase Selection
# phase_tag = "Iguanas 1st launch"
# phase_tag = "Iguanas 2nd launch"
# phase_tag = "Iguanas 3rd launch"
phase_tag = "Iguanas 4th launch"


debug = False # debugging with a smaller dataset
plot_diagrams = False # plot the diagrams to disk for the clustering methods
show_plots = False # show the plots in the notebook

user_threshold = None # None or a number, filter records which have less than these user interactions.
use_gold_standard_subset = None # Use no filtering


## Input Path of all the data
input_path =Path("/Users/christian/data/zooniverse")
# input_path = Path("results/")
# Location for the analysis Results
output_path = Path(input_path.joinpath(f"2024_09_02_analysis").joinpath(phase_tag))
output_path.mkdir(exist_ok=True, parents=True)
reprocess = False # if True, the raw classification data is reprocessed. If False, the data is loaded from disk

# Location for plots
# output_plot_path = output_path.joinpath("plots")
# output_plot_path.mkdir(parents=True, exist_ok=True)
output_plot_path = None # do not plot

## Look into the config
This Config points to all files necessary for the analysis + the result files

In [8]:
from zooniverse.config import get_config

config = get_config(phase_tag=phase_tag, input_path=input_path, output_path=output_path)
config

{'annotations_source': PosixPath('/Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-classifications.csv'),
 'goldstandard_data': PosixPath('/Users/christian/data/zooniverse/Images/Zooniverse_Goldstandard_images/expert-GS-4thphase_renamed.csv'),
 'gold_standard_image_subset': PosixPath('/Users/christian/data/zooniverse/Images/Zooniverse_Goldstandard_images/4-T2-GS-results-5th-0s.csv'),
 'image_source': None,
 'subjects_path': PosixPath('/Users/christian/data/zooniverse/IguanasFromAbove/2024-08-08/iguanas-from-above-subjects.csv'),
 'yes_no_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/yes_no_dataset_Iguanas 4th launch.csv'),
 'flat_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/flat_dataset_Iguanas 4th launch.csv'),
 'flat_panoptes_points': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/flat_panoptes_points_Iguanas 4th launch.csv'),
 'panoptes_question': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/panoptes_question_Iguanas 4th launch.csv'),
 'merged_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/flat_dataset_filtered_Iguanas 4th launch.csv'),
 'gold_standard_and_expert_count': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_gold_standard_and_expert_count.csv'),
 'comparison_dataset': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison.csv'),
 'comparison_dataset_expert': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison_expert.csv'),
 'comparison_dataset_yes_no': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison_yes_no.csv'),
 'method_sums': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_method_sums.csv'),
 'rmse_errors': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_rmse_errors.csv'),
 'dbscan_hyperparam_grid': PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_hyperparam_grid.csv')}

In [9]:
config["flat_panoptes_points"]

PosixPath('/Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/flat_panoptes_points_Iguanas 4th launch.csv')

## Look at the data

In [10]:

df_flat_panoptes_points = pd.read_csv(config["flat_panoptes_points"])
df_flat_panoptes_points["phase"] = phase_tag

df_flat_panoptes_points

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y,phase
0,525501702,2c71cd336686d99b2fddf9bf5c5e2d86,0013808b3d09505e4e150c365ee48a43,25351,51.133,T2,2023-11-29 02:20:34 UTC,92466390,Isa_ISCWN02_18012023_81_36.jpg,335,655,Iguanas 4th launch
1,537681646,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:15:54 UTC,92461153,Fer_FPE01-06_18122021_32_33.jpg,16,245,Iguanas 4th launch
2,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,652,596,Iguanas 4th launch
3,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,233,561,Iguanas 4th launch
4,537681792,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:16:38 UTC,92465107,Fer_FPM01-02_20012023_52_74.jpg,67,594,Iguanas 4th launch
...,...,...,...,...,...,...,...,...,...,...,...,...
187113,563671982,ff34a702faa50d4664aaa32e1f4aa569,NaN,25351,51.133,T2,2024-05-24 17:24:30 UTC,92469726,Isa_ISVB01_27012023_75_37.jpg,349,122,Iguanas 4th launch
187114,518717765,9b7e5901c61869dc6c15ef440db39903,NaN,25351,51.133,T2,2023-10-26 22:26:33 UTC,92469727,Isa_ISVB02_27012023_154.jpg,456,129,Iguanas 4th launch
187115,518469002,1d23a3d52d2335e30eda5f7fd35beb05,NaN,25351,51.133,T2,2023-10-26 01:01:00 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,582,657,Iguanas 4th launch
187116,535441276,b6254211ad7527a1e3d29e0d8ba29660,NaN,25351,51.133,T2,2024-01-18 22:56:05 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,599,675,Iguanas 4th launch
187117,518215148,57c0288002e097cae09fb1178cba0ba2,NaN,25351,51.133,T2,2023-10-24 22:09:30 UTC,92469734,Isa_ISVB01_27012023_27_16.jpg,230,590,Iguanas 4th launch

### Filter User if necessary and Marks

In [11]:
# Use the panoptes Extraction instead of the custom extraction
df_merged_dataset = df_flat_panoptes_points

### Are there anonymous users in the data?
There should be some because anonymous users are kept.

In [12]:
df_merged_dataset[df_merged_dataset.user_id.isnull().values]

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y,phase
153773,517799401,c7382eb29b1780b9dda0834c2be962f6,NaN,25351,51.133,T2,2023-10-23 08:21:05 UTC,92458387,Fer_FCD01-02-03_20122021_22_18.jpg,569,499,Iguanas 4th launch
153774,517799401,c7382eb29b1780b9dda0834c2be962f6,NaN,25351,51.133,T2,2023-10-23 08:21:05 UTC,92458387,Fer_FCD01-02-03_20122021_22_18.jpg,421,111,Iguanas 4th launch
153775,517799401,c7382eb29b1780b9dda0834c2be962f6,NaN,25351,51.133,T2,2023-10-23 08:21:05 UTC,92458387,Fer_FCD01-02-03_20122021_22_18.jpg,162,638,Iguanas 4th launch
153776,517799401,c7382eb29b1780b9dda0834c2be962f6,NaN,25351,51.133,T2,2023-10-23 08:21:05 UTC,92458387,Fer_FCD01-02-03_20122021_22_18.jpg,547,681,Iguanas 4th launch
153777,517799401,c7382eb29b1780b9dda0834c2be962f6,NaN,25351,51.133,T2,2023-10-23 08:21:05 UTC,92458387,Fer_FCD01-02-03_20122021_22_18.jpg,627,589,Iguanas 4th launch
...,...,...,...,...,...,...,...,...,...,...,...,...
187113,563671982,ff34a702faa50d4664aaa32e1f4aa569,NaN,25351,51.133,T2,2024-05-24 17:24:30 UTC,92469726,Isa_ISVB01_27012023_75_37.jpg,349,122,Iguanas 4th launch
187114,518717765,9b7e5901c61869dc6c15ef440db39903,NaN,25351,51.133,T2,2023-10-26 22:26:33 UTC,92469727,Isa_ISVB02_27012023_154.jpg,456,129,Iguanas 4th launch
187115,518469002,1d23a3d52d2335e30eda5f7fd35beb05,NaN,25351,51.133,T2,2023-10-26 01:01:00 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,582,657,Iguanas 4th launch
187116,535441276,b6254211ad7527a1e3d29e0d8ba29660,NaN,25351,51.133,T2,2024-01-18 22:56:05 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,599,675,Iguanas 4th launch
187117,518215148,57c0288002e097cae09fb1178cba0ba2,NaN,25351,51.133,T2,2023-10-24 22:09:30 UTC,92469734,Isa_ISVB01_27012023_27_16.jpg,230,590,Iguanas 4th launch

In [13]:
# Amount of images
df_merged_dataset["subject_id"].nunique()

4682

In [14]:
## After filtering there
df_merged_dataset

,classification_id,user_name,user_id,workflow_id,workflow_version,task,created_at,subject_id,image_name,x,y,phase
0,525501702,2c71cd336686d99b2fddf9bf5c5e2d86,0013808b3d09505e4e150c365ee48a43,25351,51.133,T2,2023-11-29 02:20:34 UTC,92466390,Isa_ISCWN02_18012023_81_36.jpg,335,655,Iguanas 4th launch
1,537681646,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:15:54 UTC,92461153,Fer_FPE01-06_18122021_32_33.jpg,16,245,Iguanas 4th launch
2,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,652,596,Iguanas 4th launch
3,537682677,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:20:06 UTC,92463273,Fer_FPM01-02_20012023_26_108.jpg,233,561,Iguanas 4th launch
4,537681792,10994132e025a2d3bee8971688da1fe5,003883280e2befdf34edfb257bd8a791,25351,51.133,T2,2024-01-26 16:16:38 UTC,92465107,Fer_FPM01-02_20012023_52_74.jpg,67,594,Iguanas 4th launch
...,...,...,...,...,...,...,...,...,...,...,...,...
187113,563671982,ff34a702faa50d4664aaa32e1f4aa569,NaN,25351,51.133,T2,2024-05-24 17:24:30 UTC,92469726,Isa_ISVB01_27012023_75_37.jpg,349,122,Iguanas 4th launch
187114,518717765,9b7e5901c61869dc6c15ef440db39903,NaN,25351,51.133,T2,2023-10-26 22:26:33 UTC,92469727,Isa_ISVB02_27012023_154.jpg,456,129,Iguanas 4th launch
187115,518469002,1d23a3d52d2335e30eda5f7fd35beb05,NaN,25351,51.133,T2,2023-10-26 01:01:00 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,582,657,Iguanas 4th launch
187116,535441276,b6254211ad7527a1e3d29e0d8ba29660,NaN,25351,51.133,T2,2024-01-18 22:56:05 UTC,92469733,Isa_ISVB01_27012023_75_36.jpg,599,675,Iguanas 4th launch
187117,518215148,57c0288002e097cae09fb1178cba0ba2,NaN,25351,51.133,T2,2023-10-24 22:09:30 UTC,92469734,Isa_ISVB01_27012023_27_16.jpg,230,590,Iguanas 4th launch

In [15]:
# how many marks per user
df_merged_dataset[["user_id", "user_name", "x"]].groupby("user_name").count()

                                  user_id   x
user_name
00372150856af1a3375df35b7d37add7        0   3
0066711974a94f9a809144c6c1a9d50e       15  15
0095887c38d0bf96dac7edbdcb1b5626        0  10
00b40bb9fbb47ff6689ed51150d04070       31  31
00d13c63213acb316c8563ba075fde46        5   5
...                                   ...  ..
ff31f7f999ad47f19b54a96da8c4a348        0  10
ff34a702faa50d4664aaa32e1f4aa569        0   2
ff9737a42300765b991f2b9adcee645b        0   4
ffbf763977ba25dfaebbe49e409c8fe6        0  21
ffe19fb42b2e16f2bb901484a77810b0        2   2

[2647 rows x 2 columns]

## Clustering

### Basic Statics like mean, median, mode

In [16]:
from zooniverse.analysis import get_mark_overview

basic_stats = []

for image_name, df_image_name in df_merged_dataset.groupby("subject_id"):
    annotations_count = get_mark_overview(df_image_name)

    annotations_count_stats = get_annotation_count_stats(annotations_count=annotations_count,
                                                         image_name=df_image_name.iloc[0]["image_name"], 
                                                         subject_id=df_image_name.iloc[0]["subject_id"])

    ### basic statistics like mean, median, mode
    basic_stats.append(annotations_count_stats)
    

df_basic_stats = pd.DataFrame(basic_stats)    
df_comparison = df_basic_stats

In [17]:
df_basic_stats

,image_name,subject_id,median_count,mean_count,mode_min_count,mode_max_count,mode_count,mode_count_avg,users,sum_annotations_count,annotations_count
0,Fer_FCD01-02-03_20122021_22_18.jpg,92458387,61.0,60.63,59,68,"[59, 68]",63.5,19,1152,"[19, 38, 40, 46, 52, 58, 59, 59, 60, 61, 63, 6..."
1,Fer_FCD01-02-03_20122021_38_40.jpg,92458388,2.0,2.00,2,2,[2],2.0,14,28,"[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]"
2,Fer_FCD01-02-03_20122021_70_10.jpg,92458389,3.0,3.33,1,1,[1],1.0,15,50,"[1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 9]"
3,Fer_FCD01-02-03_20122021_6_24.jpg,92458390,6.0,5.38,6,6,[6],6.0,16,86,"[2, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7]"
4,Fer_FCD01-02-03_20122021_56_14.jpg,92458394,4.0,4.09,6,6,[6],6.0,11,45,"[1, 2, 3, 3, 4, 4, 4, 6, 6, 6, 6]"
...,...,...,...,...,...,...,...,...,...,...,...
4677,Isa_ISVB02_27012023_154.jpg,92469727,1.0,1.00,1,1,[1],1.0,3,3,"[1, 1, 1]"
4678,Isa_ISVB01_27012023_49_43.jpg,92469728,1.0,1.00,1,1,[1],1.0,2,2,"[1, 1]"
4679,Isa_ISVB02_27012023_155.jpg,92469731,3.0,2.89,3,3,[3],3.0,9,26,"[2, 3, 3, 3, 3, 3, 3, 3, 3]"
4680,Isa_ISVB01_27012023_75_36.jpg,92469733,1.0,1.00,1,1,[1],1.0,18,18,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4681,Isa_ISVB01_27012023_27_16.jpg,92469734,1.0,1.00,1,1,[1],1.0,17,17,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [18]:
# There might be records with too few annotations if they were not removed before
df_comparison[(df_comparison.sum_annotations_count < 5)].sort_values(by="users", ascending=False)

,image_name,subject_id,median_count,mean_count,mode_min_count,mode_max_count,mode_count,mode_count_avg,users,sum_annotations_count,annotations_count
16,Fer_FCD01-02-03_20122021_34_40.jpg,92458418,1.0,1.0,1,1,[1],1.0,4,4,"[1, 1, 1, 1]"
105,Fer_FCD01-02-03_20122021_32_30.jpg,92458583,1.0,1.0,1,1,[1],1.0,4,4,"[1, 1, 1, 1]"
3186,Fer_FPM01-02_20012023_55_74.jpg,92464804,1.0,1.0,1,1,[1],1.0,4,4,"[1, 1, 1, 1]"
3182,Fer_FPM01-02_20012023_46_20.jpg,92464799,1.0,1.0,1,1,[1],1.0,4,4,"[1, 1, 1, 1]"
3153,Fer_FPM01-02_20012023_58_8.jpg,92464753,1.0,1.0,1,1,[1],1.0,4,4,"[1, 1, 1, 1]"
...,...,...,...,...,...,...,...,...,...,...,...
2472,Fer_FPM01-02_20012023_29_101.jpg,92463610,1.0,1.0,1,1,[1],1.0,1,1,[1]
2465,Fer_FPM01-02_20012023_38_71.jpg,92463599,2.0,2.0,2,2,[2],2.0,1,2,[2]
2464,Fer_FPM01-02_20012023_25_127.jpg,92463598,1.0,1.0,1,1,[1],1.0,1,1,[1]
2462,Fer_FPM01-02_20012023_42_93.jpg,92463596,1.0,1.0,1,1,[1],1.0,1,1,[1]
2681,Fer_FPM01-02_20012023_20_108.jpg,92463982,1.0,1.0,1,1,[1],1.0,1,1,[1]

In [19]:
# Fill NaN values with 0
df_comparison.fillna(0, inplace=True)

### DBSCAN clustering and take the variant with the best silouette score for each image
Grid search for the best silouette score among the permutations of eps and min_samples values.

In [20]:
## sort by silouette score sorting + dbscan_count
# from zooniverse.analysis import compare_dbscan
# 
# eps_variants = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
# min_samples_variants = [3, 5, 8, 10]
# if debug:
#     eps_variants = [0.3]
#     min_samples_variants = [3]
# params = [(eps, min_samples) for eps in eps_variants for min_samples in min_samples_variants]
# 
# db_scan_results = {}
# db_scan_best_results = []
# for image_name, df_image_name in df_merged_dataset.groupby("subject_id"):
#     # check for at least 5 marks
#     if df_image_name.shape[0] >= 5:
#         dbscan_localization = compare_dbscan(
#             params=params,
#             df_flat=df_image_name,
#             output_plot_path=output_plot_path,
#             plot=show_plots
#         )
#     
#         db_scan_results[image_name] = pd.DataFrame(dbscan_localization)
#         
#         # DBSCAN tends to classify all points as noise if min_samples is too high. Often only a single user marked an iguana.
#         # Sillouette Scoring needs a minimum of 2 clusters
#         # if there are points in decent radius they will belong to a cluster
#         if pd.DataFrame(dbscan_localization).dbscan_count.max() == 1:
#             db_scan_best_results.append(pd.DataFrame(dbscan_localization).sort_values("dbscan_count", ascending=False).iloc[0])
#             # If two or more cluster seem to exists take ones with the best Silouette score
#         else:  
#             # take the best result by silouette score if there are more clusters then 1
#             db_scan_best_results.append(pd.DataFrame(dbscan_localization).sort_values(["dbscan_silouette_score", "dbscan_count"], ascending=[False, False]).iloc[0])
#     
# df_dbscan_localization = pd.concat([*db_scan_results.values()])
# df_scan_best_results = pd.DataFrame(db_scan_best_results)

In [21]:
# df_scan_best_results

Here it can be seen why the silouette score is difficult because it is often undefined.

In [22]:
## save the combinations of parameters, which maximized the silouette score.
# df_dbscan_localization.to_csv(config["dbscan_hyperparam_grid"])

In [23]:
# df_scan_best_results.rename(columns={"dbscan_count": "dbscan_count_sil"}, inplace=True)
# 
# 
# df_comparison = df_comparison.merge(df_scan_best_results.drop(["image_name"], axis=1), on='subject_id', how='left')

In [24]:
# drop columns which are not interesting here
df_comparison = df_comparison.drop(["dbscan_noise", "dbscan_silouette_score", "eps", "min_samples", "dbscan_BIC_score", "with_noise", "bic_avg"], axis=1, errors="ignore")
df_comparison

,image_name,subject_id,median_count,mean_count,mode_min_count,mode_max_count,mode_count,mode_count_avg,users,sum_annotations_count,annotations_count
0,Fer_FCD01-02-03_20122021_22_18.jpg,92458387,61.0,60.63,59,68,"[59, 68]",63.5,19,1152,"[19, 38, 40, 46, 52, 58, 59, 59, 60, 61, 63, 6..."
1,Fer_FCD01-02-03_20122021_38_40.jpg,92458388,2.0,2.00,2,2,[2],2.0,14,28,"[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]"
2,Fer_FCD01-02-03_20122021_70_10.jpg,92458389,3.0,3.33,1,1,[1],1.0,15,50,"[1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 9]"
3,Fer_FCD01-02-03_20122021_6_24.jpg,92458390,6.0,5.38,6,6,[6],6.0,16,86,"[2, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7]"
4,Fer_FCD01-02-03_20122021_56_14.jpg,92458394,4.0,4.09,6,6,[6],6.0,11,45,"[1, 2, 3, 3, 4, 4, 4, 6, 6, 6, 6]"
...,...,...,...,...,...,...,...,...,...,...,...
4677,Isa_ISVB02_27012023_154.jpg,92469727,1.0,1.00,1,1,[1],1.0,3,3,"[1, 1, 1]"
4678,Isa_ISVB01_27012023_49_43.jpg,92469728,1.0,1.00,1,1,[1],1.0,2,2,"[1, 1]"
4679,Isa_ISVB02_27012023_155.jpg,92469731,3.0,2.89,3,3,[3],3.0,9,26,"[2, 3, 3, 3, 3, 3, 3, 3, 3]"
4680,Isa_ISVB01_27012023_75_36.jpg,92469733,1.0,1.00,1,1,[1],1.0,18,18,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4681,Isa_ISVB01_27012023_27_16.jpg,92469734,1.0,1.00,1,1,[1],1.0,17,17,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

### HDBSCAN clustering for each image

In [25]:
from zooniverse.analysis import hdbscan

hdbscan_values = []

eps_variants = [0.0] # 0 is the default
min_cluster_sizes = [5] # 5 is the default


for image_name, df_image_name in df_merged_dataset.groupby("subject_id"):
    annotations_count = get_mark_overview(df_image_name)
    
    image_name=df_image_name.iloc[0]["image_name"]
    subject_id=df_image_name.iloc[0]["subject_id"]
    
    annotations_count_stats = get_annotation_count_stats(annotations_count=annotations_count,
                                                         image_name=image_name, 
                                                         subject_id=subject_id)
    
    # if less than min_cluster_sizes points are available clustering makes no sense
    if df_image_name.shape[0] >= 5: # If num_samples is 5 for the min_cluster_size is 5 there is no point in passing data with less than 5 samples
        params = [(eps, min_cluster_size, max_cluster_size) 
                    for eps in eps_variants
                    for min_cluster_size in min_cluster_sizes
                    for max_cluster_size in [None]
              ]

        df_hdbscan = hdbscan(df_marks=df_image_name[["x", "y"]],
                                     output_path=output_plot_path,
                                     plot=show_plots,
                                     show=show_plots,
                                     image_name=image_name,
                                     subject_id=subject_id,
                                     params=params)
        hdbscan_values.append(df_hdbscan)


df_hdbscan = pd.concat(hdbscan_values)

In [26]:
df_hdbscan.drop(["with_noise"], axis=1, inplace=True)
df_hdbscan

,image_name,subject_id,HDBSCAN_count,eps,min_cluster_size,max_cluster_size,noise_points
0,Fer_FCD01-02-03_20122021_22_18.jpg,92458387,75,0.0,5,None,73
0,Fer_FCD01-02-03_20122021_38_40.jpg,92458388,2,0.0,5,None,0
0,Fer_FCD01-02-03_20122021_70_10.jpg,92458389,5,0.0,5,None,1
0,Fer_FCD01-02-03_20122021_6_24.jpg,92458390,6,0.0,5,None,2
0,Fer_FCD01-02-03_20122021_56_14.jpg,92458394,5,0.0,5,None,3
...,...,...,...,...,...,...,...
0,Isa_ISVB01_27012023_73_40.jpg,92469720,2,0.0,5,None,2
0,Isa_ISVB01_27012023_75_37.jpg,92469726,2,0.0,5,None,7
0,Isa_ISVB02_27012023_155.jpg,92469731,3,0.0,5,None,1
0,Isa_ISVB01_27012023_75_36.jpg,92469733,2,0.0,5,None,2
0,Isa_ISVB01_27012023_27_16.jpg,92469734,1,0.0,5,None,12

In [27]:
## Statistics for all images
df_comparison = df_comparison.merge(df_hdbscan.drop(["image_name"], axis=1), on=['subject_id'], how='left')
df_comparison.fillna(0, inplace=True)
df_comparison

,image_name,subject_id,median_count,mean_count,mode_min_count,mode_max_count,mode_count,mode_count_avg,users,sum_annotations_count,annotations_count,HDBSCAN_count,eps,min_cluster_size,max_cluster_size,noise_points
0,Fer_FCD01-02-03_20122021_22_18.jpg,92458387,61.0,60.63,59,68,"[59, 68]",63.5,19,1152,"[19, 38, 40, 46, 52, 58, 59, 59, 60, 61, 63, 6...",75.0,0.0,5.0,0,73.0
1,Fer_FCD01-02-03_20122021_38_40.jpg,92458388,2.0,2.00,2,2,[2],2.0,14,28,"[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]",2.0,0.0,5.0,0,0.0
2,Fer_FCD01-02-03_20122021_70_10.jpg,92458389,3.0,3.33,1,1,[1],1.0,15,50,"[1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 9]",5.0,0.0,5.0,0,1.0
3,Fer_FCD01-02-03_20122021_6_24.jpg,92458390,6.0,5.38,6,6,[6],6.0,16,86,"[2, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7]",6.0,0.0,5.0,0,2.0
4,Fer_FCD01-02-03_20122021_56_14.jpg,92458394,4.0,4.09,6,6,[6],6.0,11,45,"[1, 2, 3, 3, 4, 4, 4, 6, 6, 6, 6]",5.0,0.0,5.0,0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4677,Isa_ISVB02_27012023_154.jpg,92469727,1.0,1.00,1,1,[1],1.0,3,3,"[1, 1, 1]",0.0,0.0,0.0,0,0.0
4678,Isa_ISVB01_27012023_49_43.jpg,92469728,1.0,1.00,1,1,[1],1.0,2,2,"[1, 1]",0.0,0.0,0.0,0,0.0
4679,Isa_ISVB02_27012023_155.jpg,92469731,3.0,2.89,3,3,[3],3.0,9,26,"[2, 3, 3, 3, 3, 3, 3, 3, 3]",3.0,0.0,5.0,0,1.0
4680,Isa_ISVB01_27012023_75_36.jpg,92469733,1.0,1.00,1,1,[1],1.0,18,18,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2.0,0.0,5.0,0,2.0
4681,Isa_ISVB01_27012023_27_16.jpg,92469734,1.0,1.00,1,1,[1],1.0,17,17,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1.0,0.0,5.0,0,12.0

In [28]:
df_panoptes_question = pd.read_csv(config["panoptes_question"])
df_panoptes_question

      subject_id  data.no  data.yes
0       92458387      0.0      22.0
1       92458388      4.0      16.0
2       92458389      3.0      17.0
3       92458390      1.0      19.0
4       92458391     21.0       0.0
...          ...      ...       ...
9923    92469731      9.0      11.0
9924    92469733      0.0      20.0
9925    92469734      1.0      19.0
9926    92469735     20.0       0.0
9927    92469736     21.0       0.0

[9928 rows x 3 columns]

In [29]:
df_comparison.to_csv(config["comparison_dataset"])
print(f"saved {config['comparison_dataset']}")

saved /Users/christian/data/zooniverse/2024_09_02_analysis/Iguanas 4th launch/Iguanas 4th launch_method_comparison.csv

## Join the Expert Dataset for comparison
This dataset contains total_counts found by experts.

In [ ]:
df_expert_count = pd.read_csv(config["goldstandard_data"], sep=";")
# check what is in there
df_expert_count[df_expert_count.image_name == "ESCG02-1_19.jpg"]

In [ ]:
## join the gold standard data to the basic stats
df_comparison_expert = df_expert_count[["site_name", "subject_group", "image_name", "subject_id", "count_total"]].merge(df_comparison.drop(["image_name"], axis=1), on='subject_id', how='left')

columns_to_fill = ['median_count', 'mean_count', 'mode_min_count', 'mode_max_count',
       'mode_count', 'mode_count_avg', 'users', 'sum_annotations_count',
        'dbscan_count_sil', 'HDBSCAN_count']
df_comparison_expert[columns_to_fill] = df_comparison_expert[columns_to_fill].fillna(0)

df_comparison_expert.sort_values(by="median_count", ascending=False)

In [ ]:
print(f"df_comparison_expert: {config['comparison_dataset_expert']}")
df_comparison_expert.to_csv(config["comparison_dataset_expert"])

In [ ]:
df_comparison_yes_no = df_comparison_expert.merge(df_panoptes_question, on="subject_id", how="left")
df_comparison_yes_no

In [ ]:
df_comparison_yes_no.to_csv(config["comparison_dataset_yes_no"])
df_comparison_yes_no

# A look into the results

## The sum of the clustering
What is the sum of the methods

In [ ]:
df_comparison_yes_no[df_comparison_yes_no["data.yes"] >= 5]

In [ ]:
# Take only the subjects which have more or equal 5 yes votes.
df_method_sums = df_comparison_yes_no[df_comparison_yes_no["data.yes"] >= 5][["count_total", "median_count", "mean_count", "mode_min_count", "mode_max_count", "mode_count_avg", "mode_min_count", "mode_max_count", "dbscan_count_sil", "HDBSCAN_count"]].sum()
df_method_sums.to_csv(config["method_sums"])
df_method_sums

## Compare the numbers
The counts are only for images which were in the dataset after filtering.

### Sum of all the Methods

In [ ]:
print(f"{config['method_sums'].name}")
df_method_sums = pd.read_csv(config["method_sums"])
df_method_sums

### Comparison per Image Level

In [ ]:
print(f"load {config['comparison_dataset']}")
pd.read_csv(config["comparison_dataset"])